defmodule Esr.Entity.PtyProcess do
  @moduledoc """
  Generic PTY-backed peer (PR-22, 2026-05-01). Owns one OS process
  spawned via erlexec's `:pty` wrapper. Fans raw stdout chunks to
  Phoenix.PubSub topic `"pty:<session_id>"` for `EsrWeb.AttachLive`
  subscribers; accepts stdin via the public `write/2` and SIGWINCH via
  `resize/3`.

  cc_process is **not** a PubSub subscriber here — the conversation path
  is cc_mcp → `cli:channel/<sid>`. PtyProcess only serves the operator-
  facing browser attach.

  ## Process structure

  - `start_link/1` starts `__MODULE__.OSProcessWorker` (generated by the
    `use Esr.OSProcess` macro). The worker holds the GenServer mailbox.
  - `init/1` runs inside the worker and registers under
    `Esr.Entity.Registry` with the binary actor_id `"pty:<sid>"` so
    `EsrWeb.AttachLive` can find this peer to forward stdin/resize.
  - `on_raw_stdout/2` (new optional `Esr.OSProcess` callback) fires
    BEFORE line-splitting, broadcasting raw bytes so ANSI escapes
    spanning chunk boundaries reach xterm.js intact.
  - `handle_downstream(:rewire_siblings, state)` runs the PR-21ω' rewire
    inlined here (no separate `PeerRewire` module).
  - `on_terminate/1` broadcasts a bare `:pty_closed` so attached
    LiveViews can render a "session ended" overlay.
  """

  require Logger

  @behaviour Esr.Role.State

  use Esr.Entity.Stateful
  use Esr.OSProcess, kind: :pty, wrapper: :pty

  alias Phoenix.PubSub

  # ------------------------------------------------------------------
  # Boot
  # ------------------------------------------------------------------

  def start_link(args) do
    args = Map.put_new(args, :subscriber, self())
    GenServer.start_link(__MODULE__.OSProcessWorker, args, name: name_for(args))
  end

  def child_spec(args) do
    %{
      id: __MODULE__,
      start: {__MODULE__, :start_link, [args]},
      type: :worker,
      restart: :transient,
      shutdown: 5_000
    }
  end

  @impl Esr.Entity
  def spawn_args(params) do
    name = "esr_pty_#{:erlang.unique_integer([:positive])}"

    %{
      session_name: name,
      dir: Esr.Entity.get_param(params, :dir) || "/tmp",
      session_id: Esr.Entity.get_param(params, :session_id),
      workspace_name: Esr.Entity.get_param(params, :workspace_name),
      chat_id: Esr.Entity.get_param(params, :chat_id),
      app_id: Esr.Entity.get_param(params, :app_id),
      start_cmd: Esr.Entity.get_param(params, :start_cmd)
    }
  end

  # ------------------------------------------------------------------
  # Public API (called from EsrWeb.AttachLive event handlers)
  # ------------------------------------------------------------------

  @doc "Forward keystrokes from xterm.js to the wrapped process's stdin."
  @spec write(String.t(), iodata()) :: :ok | {:error, term()}
  def write(sid, data) when is_binary(sid) do
    # DIAGNOSTIC (temporary 2026-05-02): log every stdin write to confirm
    # the send_input path actually reaches the PTY worker.
    require Logger
    bytes = IO.iodata_to_binary(data)
    digest = bytes |> :binary.bin_to_list() |> Enum.filter(&(&1 in 32..126 or &1 == 10)) |> List.to_string() |> String.slice(0, 200)
    Logger.info("pty.write sid=#{sid} bytes=#{byte_size(bytes)} digest=#{inspect(digest)}")

    case Esr.Entity.Registry.lookup("pty:" <> sid) do
      {:ok, worker_pid} ->
        __MODULE__.OSProcessWorker.write_stdin(worker_pid, data)

      :error ->
        Logger.warning("pty.write sid=#{sid} no PTY worker registered")
        {:error, :no_pty_for_session}
    end
  end

  @doc "Forward window-size change from xterm.js (SIGWINCH)."
  @spec resize(String.t(), pos_integer(), pos_integer()) :: :ok | {:error, term()}
  def resize(sid, cols, rows)
      when is_binary(sid) and is_integer(cols) and is_integer(rows) and cols > 0 and rows > 0 do
    case Esr.Entity.Registry.lookup("pty:" <> sid) do
      {:ok, worker_pid} -> GenServer.cast(worker_pid, {:winsz, cols, rows})
      :error -> {:error, :no_pty_for_session}
    end
  end

  # ------------------------------------------------------------------
  # Peer init — registers in Entity.Registry, schedules rewire + trust
  # confirmation timers (gated for test env)
  # ------------------------------------------------------------------

  def init(%{session_name: _, dir: _} = args) do
    state = %{
      session_name: args.session_name,
      dir: args.dir,
      subscribers: [args[:subscriber] || self()],
      neighbors: Map.get(args, :neighbors, []),
      session_id: Map.get(args, :session_id),
      workspace_name: Map.get(args, :workspace_name),
      chat_id: Map.get(args, :chat_id),
      app_id: Map.get(args, :app_id),
      start_cmd: Map.get(args, :start_cmd)
    }

    sid = state.session_id

    # Register so AttachLive can find this peer by sid. Best-effort —
    # in unit tests we may run without a registered Entity.Registry; the
    # rest of the peer still works without registration.
    if is_binary(sid) and sid != "" do
      _ =
        try do
          Esr.Entity.Registry.register("pty:" <> sid, self())
        catch
          _, _ -> :error
        end
    end

    # Deferred rewire: must NOT call back into peers_sup synchronously
    # from init (deadlock). 50ms gives DynamicSupervisor time to ack
    # this child's start_child. Gated by `:force_claude_launch` so unit
    # tests that don't run a full pipeline can disable it.
    if is_binary(sid) and sid != "" and
         Application.get_env(:esr, :force_claude_launch, Mix.env() != :test) do
      Process.send_after(self(), :rewire_siblings, 50)
    end

    {:ok, state}
  end

  # No auto-confirm of trust / dev-channels dialogs: CLAUDE_FLAGS in
  # esr-cc.sh sets `--permission-mode auto` +
  # `--dangerously-load-development-channels`, and esr-cc.sh pre-trusts
  # the workspace path in `~/.claude.json`, so the trust dialog doesn't
  # render. The dev-channels dialog is answered by the operator in the
  # browser /attach page, or by the e2e helper for unattended scenarios.

  # ------------------------------------------------------------------
  # OSProcess lifecycle hooks (signatures match os_process.ex callbacks)
  # ------------------------------------------------------------------

  @impl Esr.OSProcess
  def os_cmd(state) do
    cmd = state.start_cmd || default_start_cmd()
    # erlexec accepts a single command string; bash interprets it.
    ["bash", "-c", cmd]
  end

  @impl Esr.OSProcess
  # Hand the configured `dir` (the per-session worktree path threaded
  # through from /new-session's slash → Session.New → Scope.Router)
  # to erlexec as the `:cd` option. Without this callback, OSProcess
  # falls back to BEAM's pwd, so the spawned esr-cc.sh + claude end
  # up in `~/Workspace/esr/.../runtime` instead of
  # `<root>/.worktrees/<branch>` — confusing operators and breaking
  # the per-session git isolation PR-21θ promises.
  def os_cwd(state) do
    case state.dir do
      d when is_binary(d) and d != "" -> d
      _ -> nil
    end
  end

  @impl Esr.OSProcess
  def os_env(state) do
    case Map.get(state, :session_id) do
      sid when is_binary(sid) and sid != "" ->
        ws = Map.get(state, :workspace_name) || "default"
        chat_id = Map.get(state, :chat_id) || ""
        app_id = Map.get(state, :app_id) || ""

        chat_ids_json =
          Jason.encode!([%{chat_id: chat_id, app_id: app_id, kind: "feishu"}])

        # Terminal capability hints. claude's TUI emits a Device
        # Attributes query (`ESC[c`) at boot and **blocks** waiting for
        # the terminal to respond with its capabilities. Under iTerm
        # the shell answers immediately; under erlexec PTY launched
        # from launchd, no `TERM` is inherited (PR-21σ deliberately
        # does not source ~/.zshrc), so claude defaults to dumb mode
        # and stalls before printing its banner — observed live
        # 2026-05-01 with diagnostic raw-stdout logging. Pinning a
        # real terminal type plus reasonable size + UTF-8 locale
        # unblocks the boot path; xterm.js attaches later and
        # re-syncs the dimensions via the `resize` channel event.
        [
          {"ESR_SESSION_ID", sid},
          {"ESR_WORKSPACE", ws},
          {"ESR_CHAT_IDS", chat_ids_json},
          {"ESR_ESRD_URL", channel_ws_url()},
          {"TERM", "xterm-256color"},
          {"COLUMNS", "120"},
          {"LINES", "40"},
          {"LANG", "en_US.UTF-8"}
        ]

      _ ->
        []
    end
  end

  @impl Esr.OSProcess
  # PR-22 raw-stdout hook — fires BEFORE line-splitting, so xterm.js
  # gets ANSI escape sequences intact across chunk boundaries.
  def on_raw_stdout(data, %{session_id: sid}) when is_binary(sid) and sid != "" do
    # DIAGNOSTIC (re-enabled 2026-05-02): TERM=xterm-256color didn't
    # unblock claude — observe the full PTY output stream + stdin
    # writes to find the real bottleneck. Remove once verified.
    digest =
      data
      |> :binary.bin_to_list()
      |> Enum.filter(&(&1 in 32..126 or &1 == 10))
      |> List.to_string()
      |> String.slice(0, 300)

    if digest != "" do
      require Logger
      Logger.info("pty_stdout sid=#{sid} bytes=#{byte_size(data)} digest=#{inspect(digest)}")
    end

    PubSub.broadcast(EsrWeb.PubSub, "pty:" <> sid, {:pty_stdout, data})
    :ok
  end

  def on_raw_stdout(_data, _state), do: :ok

  @impl Esr.OSProcess
  # PR-21ω'' carryover: any process exit (even 0) triggers peers
  # DynamicSupervisor's :transient restart so a fresh peer + claude
  # come back. PR-21ω' rewire patches siblings via :pty_process key.
  def on_os_exit(0, _state), do: {:stop, :pty_died_unexpectedly}
  def on_os_exit(status, _state), do: {:stop, {:pty_crashed, status}}

  @impl Esr.OSProcess
  # 1-arg per Esr.OSProcess @callback. No reason available; broadcast
  # bare :pty_closed so AttachLive can render the "session ended" overlay.
  def on_terminate(state) do
    case Map.get(state, :session_id) do
      sid when is_binary(sid) and sid != "" ->
        PubSub.broadcast(EsrWeb.PubSub, "pty:" <> sid, :pty_closed)

      _ ->
        :ok
    end

    :ok
  end

  # ------------------------------------------------------------------
  # Peer.Stateful — upstream events (line-split stdout) are no-ops
  # here; raw bytes are handled in on_raw_stdout/2 above.
  # ------------------------------------------------------------------

  @impl Esr.Entity.Stateful
  def handle_upstream(_msg, state), do: {:forward, [], state}

  # ------------------------------------------------------------------
  # Peer.Stateful — downstream events arrive when init's send_after
  # delivers messages (rewire, trust-confirm) or when sibling peers
  # send us commands.
  # ------------------------------------------------------------------

  @impl Esr.Entity.Stateful
  def handle_downstream(:rewire_siblings, state) do
    rewire_session_siblings(state)
    {:forward, [], state}
  end

  def handle_downstream(_msg, state), do: {:forward, [], state}

  # ------------------------------------------------------------------
  # Sibling rewire (PR-21ω'). Public for the rewire test in Phase 4.
  # ------------------------------------------------------------------

  @doc false
  def rewire_session_siblings(%{session_id: sid}) when is_binary(sid) and sid != "" do
    peers_sup_via = {:via, Registry, {Esr.Scope.Registry, {:peers_sup, sid}}}

    case GenServer.whereis(peers_sup_via) do
      nil ->
        :ok

      sup_pid ->
        my_pid = self()

        sup_pid
        |> DynamicSupervisor.which_children()
        |> Enum.each(fn
          {_id, child_pid, _type, _modules} when is_pid(child_pid) and child_pid != my_pid ->
            patch_neighbor_in_state(child_pid, :pty_process, my_pid)

          _ ->
            :ok
        end)
    end
  rescue
    _ -> :ok
  catch
    :exit, _ -> :ok
  end

  def rewire_session_siblings(_state), do: :ok

  defp patch_neighbor_in_state(pid, name, new_pid) do
    _ =
      :sys.replace_state(pid, fn
        %{parent: _, state: inner} = ws when is_map(inner) ->
          %{ws | state: %{inner | neighbors: Keyword.put(inner.neighbors, name, new_pid)}}

        %{neighbors: nb} = s when is_list(nb) ->
          %{s | neighbors: Keyword.put(nb, name, new_pid)}

        other ->
          other
      end)

    :ok
  rescue
    _ -> :ok
  catch
    :exit, _ -> :ok
  end

  # ------------------------------------------------------------------
  # Helpers
  # ------------------------------------------------------------------

  defp name_for(%{session_name: n}), do: String.to_atom("esr_pty_#{n}")

  defp default_start_cmd do
    Path.join([Application.app_dir(:esr), "..", "..", "..", "scripts", "esr-cc.sh"])
    |> Path.expand()
  end

  # Returns the esrd base WebSocket URL for cc_mcp's ESR_ESRD_URL env.
  # cc_mcp's ws_client.py appends `/channel/socket/websocket?vsn=2.0.0`
  # itself — we must return JUST the base (ws://host:port), no path.
  defp channel_ws_url do
    case Application.get_env(:esr, EsrWeb.Endpoint) do
      nil ->
        "ws://localhost:4001"

      cfg ->
        url = Keyword.get(cfg, :url, [])
        host = Keyword.get(url, :host, "localhost")
        port = Keyword.get(url, :port) || Keyword.get(cfg, :http, [])[:port] || 4001
        "ws://#{host}:#{port}"
    end
  end
end
