defmodule Esr.Entity.PtyProcess do
  @moduledoc """
  Generic PTY-backed peer (PR-22, 2026-05-01; M-2.6 multi-instance,
  resource-typed grammar PR pubsub topic migration). Owns one OS process
  spawned via erlexec's `:pty` wrapper. Fans raw stdout chunks to
  Phoenix.PubSub topic `"pty:<actor_id>"` for `EsrWeb.PtySocket`
  subscribers; accepts stdin via the public `write/2` and SIGWINCH via
  `resize/3`.

  ## Identity

  Each PtyProcess registers under `Esr.Entity.Registry` with the binary
  actor_id `"pty:<actor_id>"` (where `actor_id` is the per-instance UUID
  generated by `Esr.Entity.Agent.InstanceRegistry.add_instance_and_spawn/2`).
  Pre-resource-typed-grammar this used `"pty:<session_id>"`, which broke
  multi-agent attach: N PtyProcesses in one session collided on the
  register key + PubSub topic.

  ## Subscribers

  - `EsrWeb.PtySocket` subscribes to `pty:<actor_id>` to fan stdout to
    the browser.
  - cc_process is **not** a subscriber — the conversation path is
    cc_mcp → `cli:channel/<sid>`. PtyProcess only serves the operator-
    facing browser attach.

  ## Process structure

  - `start_link/1` starts `__MODULE__.OSProcessWorker` (generated by the
    `use Esr.OSProcess` macro).
  - `init/1` registers under `Esr.Entity.Registry` AND in Index 2/3 via
    `register_attrs/2` so `Esr.ActorQuery.{find_by_name/2, list_by_role/2}`
    resolve this peer.
  - `on_raw_stdout/2` broadcasts raw bytes BEFORE line-splitting so ANSI
    escapes spanning chunk boundaries reach xterm.js intact.
  - `on_terminate/1` broadcasts a bare `:pty_closed` so attached sockets
    can render a "session ended" overlay.
  """

  require Logger

  @behaviour Esr.Role.State

  use Esr.Entity.Stateful
  use Esr.OSProcess, kind: :pty, wrapper: :pty

  alias Phoenix.PubSub

  # M-1.5: compile-time role constant. Consumed by `register_attrs/2`
  # in init/1 below and by `deregister_attrs/2` in terminate/2 so a
  # rename happens in exactly one place. `Esr.ActorQuery.list_by_role/2`
  # callers (M-2+) match against this atom.
  @role :pty_process

  # ------------------------------------------------------------------
  # Boot
  # ------------------------------------------------------------------

  def start_link(args) do
    args = Map.put_new(args, :subscriber, self())
    GenServer.start_link(__MODULE__.OSProcessWorker, args, name: name_for(args))
  end

  def child_spec(args) do
    %{
      id: __MODULE__,
      start: {__MODULE__, :start_link, [args]},
      type: :worker,
      restart: :transient,
      shutdown: 5_000
    }
  end

  @impl Esr.Entity
  def spawn_args(params) do
    name = "esr_pty_#{:erlang.unique_integer([:positive])}"

    %{
      session_name: name,
      dir: Esr.Entity.get_param(params, :dir) || "/tmp",
      session_id: Esr.Entity.get_param(params, :session_id),
      workspace_name: Esr.Entity.get_param(params, :workspace_name),
      chat_id: Esr.Entity.get_param(params, :chat_id),
      app_id: Esr.Entity.get_param(params, :app_id),
      start_cmd: Esr.Entity.get_param(params, :start_cmd)
    }
  end

  # ------------------------------------------------------------------
  # Public API (called from EsrWeb.AttachLive event handlers)
  # ------------------------------------------------------------------

  @doc "Forward keystrokes from xterm.js to the wrapped process's stdin."
  @spec write(String.t(), iodata()) :: :ok | {:error, term()}
  def write(sid, data) when is_binary(sid) do
    # DIAGNOSTIC (temporary 2026-05-02): log every stdin write to confirm
    # the send_input path actually reaches the PTY worker.
    require Logger
    bytes = IO.iodata_to_binary(data)
    digest = bytes |> :binary.bin_to_list() |> Enum.filter(&(&1 in 32..126 or &1 == 10)) |> List.to_string() |> String.slice(0, 200)
    Logger.info("pty.write sid=#{sid} bytes=#{byte_size(bytes)} digest=#{inspect(digest)}")

    case Esr.Entity.Registry.lookup("pty:" <> sid) do
      {:ok, worker_pid} ->
        __MODULE__.OSProcessWorker.write_stdin(worker_pid, data)

      :error ->
        Logger.warning("pty.write sid=#{sid} no PTY worker registered")
        {:error, :no_pty_for_session}
    end
  end

  @doc "Forward window-size change from xterm.js (SIGWINCH)."
  @spec resize(String.t(), pos_integer(), pos_integer()) :: :ok | {:error, term()}
  def resize(sid, cols, rows)
      when is_binary(sid) and is_integer(cols) and is_integer(rows) and cols > 0 and rows > 0 do
    case Esr.Entity.Registry.lookup("pty:" <> sid) do
      {:ok, worker_pid} -> GenServer.cast(worker_pid, {:winsz, cols, rows})
      :error -> {:error, :no_pty_for_session}
    end
  end

  # ------------------------------------------------------------------
  # Peer init — registers in Entity.Registry (Index 1/2/3); ActorQuery
  # is now the only neighbor lookup mechanism.
  # ------------------------------------------------------------------

  def init(%{session_name: _, dir: _} = args) do
    state = %{
      session_name: args.session_name,
      dir: args.dir,
      subscribers: [args[:subscriber] || self()],
      session_id: Map.get(args, :session_id),
      actor_id: Map.get(args, :actor_id),
      workspace_name: Map.get(args, :workspace_name),
      chat_id: Map.get(args, :chat_id),
      app_id: Map.get(args, :app_id),
      start_cmd: Map.get(args, :start_cmd)
    }

    sid = state.session_id
    # Phase A.4 (resource-typed grammar): register key + Index 2/3 attrs +
    # PubSub broadcasts now key on actor_id, not session_id. M-2.6 multi-
    # agent sessions spawn N PtyProcesses for one session_id; the old
    # session_id keying silently collided (second register overwrote first,
    # broadcasts muxed). build_pty_args/4 in InstanceRegistry threads the
    # actor_id UUID through; defensive `|| sid` keeps unit-test paths that
    # bypass build_pty_args/4 working.
    actor_id = Map.get(args, :actor_id) || sid

    # Register so PtySocket can find this peer by actor_id. Best-effort —
    # in unit tests we may run without a registered Entity.Registry; the
    # rest of the peer still works without registration.
    if is_binary(actor_id) and actor_id != "" do
      _ =
        try do
          Esr.Entity.Registry.register("pty:" <> actor_id, self())
        catch
          _, _ -> :error
        end

      # M-1.5: also register in Index 2 (`{sid, name}`) and Index 3
      # (`{sid, role}`) so `Esr.ActorQuery.find_by_name/2` and
      # `list_by_role/2` resolve this peer. Reuse the same string as
      # the Index 1 actor_id ("pty:<actor_id>") so cross-references stay
      # in sync. The inner `session_id: sid` attribute remains a SEARCHABLE
      # field for ActorQuery — only the registry key migrates to actor_id.
      # Best-effort guard: unit tests that bypass the application supervisor
      # (no IndexWatcher / no ETS tables) must keep working.
      _ =
        try do
          Esr.Entity.Registry.register_attrs("pty:" <> actor_id, %{
            session_id: sid,
            name: Map.get(args, :name) || ("pty-" <> actor_id),
            role: @role
          })
        catch
          _, _ -> :ok
        end
    end

    {:ok, state}
  end

  # No auto-confirm of trust / dev-channels dialogs: Phase 8 deleted
  # scripts/esr-cc.sh (superseded by Esr.Plugins.ClaudeCode.Launcher).
  # Launcher sets `--permission-mode auto` +
  # `--dangerously-load-development-channels`, and pre-trusts the
  # workspace path in `~/.claude.json`, so the trust dialog doesn't
  # render. The dev-channels dialog is answered by the operator in the
  # browser /attach page, or by the e2e helper for unattended scenarios.

  # ------------------------------------------------------------------
  # OSProcess lifecycle hooks (signatures match os_process.ex callbacks)
  # ------------------------------------------------------------------

  @impl Esr.OSProcess
  # Phase 8: esr-cc.sh deleted. Use Esr.Plugins.ClaudeCode.Launcher
  # when no explicit start_cmd override is present in state.
  # start_cmd override (from workspace config) is accepted as a string
  # and wrapped with bash for backwards-compatible operator escape hatch.
  def os_cmd(state) do
    case state.start_cmd do
      cmd when is_binary(cmd) and cmd != "" ->
        # Explicit override from workspace.start_cmd — wrap with bash
        # for legacy operator scripts that may still be strings.
        ["bash", "-c", cmd]

      _ ->
        # Default: Elixir-native Launcher builds the argv.
        Esr.Plugins.ClaudeCode.Launcher.spawn_cmd(
          cwd:  Map.get(state, :dir),
          role: Map.get(state, :workspace_role, "dev")
        )
    end
  end

  @impl Esr.OSProcess
  # Hand the configured `dir` (the per-session worktree path threaded
  # through from /new-session's slash → Session.New → Scope.Router)
  # to erlexec as the `:cd` option. Without this callback, OSProcess
  # falls back to BEAM's pwd, so the spawned claude process ends
  # up in `~/Workspace/esr/.../runtime` instead of
  # `<root>/.worktrees/<branch>` — confusing operators and breaking
  # the per-session git isolation PR-21θ promises.
  def os_cwd(state) do
    case state.dir do
      d when is_binary(d) and d != "" -> d
      _ -> nil
    end
  end

  @impl Esr.OSProcess
  def os_env(state) do
    case Map.get(state, :session_id) do
      sid when is_binary(sid) and sid != "" ->
        ws = Map.get(state, :workspace_name) || "default"
        chat_id = Map.get(state, :chat_id) || ""
        app_id = Map.get(state, :app_id) || ""

        chat_ids_json =
          Jason.encode!([%{chat_id: chat_id, app_id: app_id, kind: "feishu"}])

        # Terminal capability hints. claude's TUI emits a Device
        # Attributes query (`ESC[c`) at boot and **blocks** waiting for
        # the terminal to respond with its capabilities. Under iTerm
        # the shell answers immediately; under erlexec PTY launched
        # from launchd, no `TERM` is inherited (PR-21σ deliberately
        # does not source ~/.zshrc), so claude defaults to dumb mode
        # and stalls before printing its banner — observed live
        # 2026-05-01 with diagnostic raw-stdout logging. Pinning a
        # real terminal type plus reasonable size + UTF-8 locale
        # unblocks the boot path; xterm.js attaches later and
        # re-syncs the dimensions via the `resize` channel event.
        base = [
          {"ESR_SESSION_ID", sid},
          {"ESR_WORKSPACE", ws},
          {"ESR_CHAT_IDS", chat_ids_json},
          {"ESR_ESRD_URL", channel_ws_url()},
          {"TERM", "xterm-256color"},
          {"COLUMNS", "120"},
          {"LINES", "40"},
          {"LANG", "en_US.UTF-8"}
        ]

        # Phase 8: merge plugin config env (proxy vars, esrd_url override)
        # from Launcher. Build with the global-layer config; PtyProcess does
        # not carry user_uuid/workspace_id so global defaults apply.
        # Launcher.build_env returns a keyword list — convert to string tuples
        # and merge (base wins on key conflicts since we append).
        launcher_env =
          try do
            Esr.Plugins.ClaudeCode.Launcher.build_env(
              plugin_config: Esr.Plugin.Config.resolve("claude_code"),
              session_id: sid
            )
            |> Enum.map(fn {k, v} -> {Atom.to_string(k), v} end)
          rescue
            _ -> []
          end

        # Merge: launcher_env first so base-env explicit values win on conflict.
        launcher_env ++ base

      _ ->
        []
    end
  end

  @impl Esr.OSProcess
  # PR-22 raw-stdout hook — fires BEFORE line-splitting, so xterm.js
  # gets ANSI escape sequences intact across chunk boundaries.
  def on_raw_stdout(data, %{session_id: sid} = state) when is_binary(sid) and sid != "" do
    # DIAGNOSTIC (re-enabled 2026-05-02): TERM=xterm-256color didn't
    # unblock claude — observe the full PTY output stream + stdin
    # writes to find the real bottleneck. Remove once verified.
    digest =
      data
      |> :binary.bin_to_list()
      |> Enum.filter(&(&1 in 32..126 or &1 == 10))
      |> List.to_string()
      |> String.slice(0, 300)

    if digest != "" do
      require Logger
      Logger.info("pty_stdout sid=#{sid} bytes=#{byte_size(data)} digest=#{inspect(digest)}")
    end

    # Phase A.4: broadcast on pty:<actor_id> for multi-agent isolation.
    # `state.actor_id || sid` keeps unit-test paths that pass `%{session_id: sid}`
    # without :actor_id working — production path always supplies actor_id via
    # InstanceRegistry.build_pty_args/4.
    topic_id = Map.get(state, :actor_id) || sid
    PubSub.broadcast(EsrWeb.PubSub, "pty:" <> topic_id, {:pty_stdout, data})
    :ok
  end

  def on_raw_stdout(_data, _state), do: :ok

  @impl Esr.OSProcess
  # PR-21ω'' carryover: any process exit (even 0) triggers peers
  # DynamicSupervisor's :transient restart so a fresh peer + claude
  # come back. New PTY's init re-registers Index 2/3 entries; siblings
  # find it via ActorQuery.list_by_role(sid, :pty_process).
  def on_os_exit(0, _state), do: {:stop, :pty_died_unexpectedly}
  def on_os_exit(status, _state), do: {:stop, {:pty_crashed, status}}

  @impl Esr.OSProcess
  # 1-arg per Esr.OSProcess @callback. No reason available; broadcast
  # bare :pty_closed so PtySocket can close the WebSocket and the
  # browser tab renders the "session ended" overlay.
  def on_terminate(state) do
    case Map.get(state, :session_id) do
      sid when is_binary(sid) and sid != "" ->
        # Phase A.4: deregister + close-broadcast key on actor_id (matches
        # the init/1 register_attrs key + on_raw_stdout broadcast topic).
        # `state.actor_id || sid` keeps unit-test paths that don't supply
        # :actor_id working.
        topic_id = Map.get(state, :actor_id) || sid

        PubSub.broadcast(EsrWeb.PubSub, "pty:" <> topic_id, :pty_closed)

        # M-1.5: deregister Index 2/3 entries on graceful shutdown. The
        # IndexWatcher monitor still cleans up if we crash before reaching
        # this hook, so this call is purely an optimization that avoids
        # a stale-entry window between shutdown signal and DOWN delivery.
        _ =
          try do
            Esr.Entity.Registry.deregister_attrs("pty:" <> topic_id, %{
              session_id: sid,
              name: Map.get(state, :name) || ("pty-" <> topic_id),
              role: @role
            })
          catch
            _, _ -> :ok
          end

      _ ->
        :ok
    end

    :ok
  end

  # ------------------------------------------------------------------
  # Peer.Stateful — upstream events (line-split stdout) are no-ops
  # here; raw bytes are handled in on_raw_stdout/2 above.
  # ------------------------------------------------------------------

  @impl Esr.Entity.Stateful
  def handle_upstream(_msg, state), do: {:forward, [], state}

  # ------------------------------------------------------------------
  # Peer.Stateful — downstream events arrive when sibling peers send
  # us commands. M-2.4: removed :rewire_siblings handler (rewire deleted).
  # ------------------------------------------------------------------

  @impl Esr.Entity.Stateful
  def handle_downstream(_msg, state), do: {:forward, [], state}

  # ------------------------------------------------------------------
  # Helpers
  # ------------------------------------------------------------------

  defp name_for(%{session_name: n}), do: String.to_atom("esr_pty_#{n}")

  # Returns the esrd base WebSocket URL for cc_mcp's ESR_ESRD_URL env.
  # cc_mcp's ws_client.py appends `/channel/socket/websocket?vsn=2.0.0`
  # itself — we must return JUST the base (ws://host:port), no path.
  defp channel_ws_url do
    case Application.get_env(:esr, EsrWeb.Endpoint) do
      nil ->
        "ws://localhost:4001"

      cfg ->
        url = Keyword.get(cfg, :url, [])
        host = Keyword.get(url, :host, "localhost")
        port = Keyword.get(url, :port) || Keyword.get(cfg, :http, [])[:port] || 4001
        "ws://#{host}:#{port}"
    end
  end
end
