defmodule Mix.Tasks.Esr.GenSlashRoutesTest do
  @moduledoc """
  Phase 4 (2026-05-09): tests for the `mix esr.gen_slash_routes` emitter.
  """

  use ExUnit.Case, async: true

  alias Mix.Tasks.Esr.GenSlashRoutes

  describe "emit/0" do
    test "starts with the AUTOGENERATED banner" do
      yaml = GenSlashRoutes.emit()
      assert yaml =~ "AUTOGENERATED — DO NOT EDIT BY HAND."
      assert yaml =~ "Source: command_meta/0"
      assert yaml =~ "mix esr.gen_slash_routes"
      assert yaml =~ "mix esr.check_command_docs"
    end

    test "schema_version is 1" do
      parsed =
        GenSlashRoutes.emit()
        |> YamlElixir.read_from_string!()

      assert parsed["schema_version"] == 1
    end

    test "includes a known slash entry with full shape" do
      parsed =
        GenSlashRoutes.emit()
        |> YamlElixir.read_from_string!()

      assert is_map(parsed["slashes"])
      assert Map.has_key?(parsed["slashes"], "/workspace:new")

      ws_new = parsed["slashes"]["/workspace:new"]
      assert ws_new["kind"] == "workspace_new"
      assert ws_new["command_module"] == "Esr.Commands.Workspace.New"
      assert ws_new["permission"] == "workspace.create"
      assert ws_new["category"] == "Workspace"
      assert is_binary(ws_new["description"])
      assert is_list(ws_new["args"])
      assert ws_new["requires_user_binding"] == true
      assert ws_new["requires_workspace_binding"] == false
    end

    test "includes an internal_kinds: section with at least one entry" do
      parsed =
        GenSlashRoutes.emit()
        |> YamlElixir.read_from_string!()

      assert is_map(parsed["internal_kinds"])
      # `reload` is a slash :none command — must appear here.
      assert Map.has_key?(parsed["internal_kinds"], "reload")

      reload = parsed["internal_kinds"]["reload"]
      assert reload["permission"] == "runtime.reload"
      assert reload["command_module"] == "Esr.Commands.Reload"
    end

    test "two consecutive emits produce byte-identical output (deterministic)" do
      a = GenSlashRoutes.emit()
      b = GenSlashRoutes.emit()
      assert a == b
    end
  end

  describe "round-trip vs on-disk yaml" do
    test "regenerated yaml has the same schema_version + slash keys + internal_kinds keys (functional view) as on-disk" do
      priv_path = Application.app_dir(:esr, "priv/slash-routes.default.yaml")
      assert File.exists?(priv_path)
      {:ok, on_disk} = YamlElixir.read_from_file(priv_path)
      generated = GenSlashRoutes.emit() |> YamlElixir.read_from_string!()

      # Schema version parity.
      assert generated["schema_version"] == on_disk["schema_version"]

      # Slash keys parity — this is what operators type, must not drift.
      assert MapSet.new(Map.keys(generated["slashes"])) ==
               MapSet.new(Map.keys(on_disk["slashes"]))

      # Internal_kinds: the registry's kind_table is populated from BOTH
      # slashes: and internal_kinds: (with internal overriding). The
      # functional view is the union of kinds across both sections. Phase 4
      # collapses redundant aliases into spec-derived form, so the literal
      # set of internal_kinds keys may shrink — but the union-of-kinds
      # parity (i.e. every kind the runtime can dispatch) must hold.
      generated_all_kinds =
        MapSet.new(
          (generated["slashes"] |> Map.values() |> Enum.map(& &1["kind"])) ++
            Map.keys(generated["internal_kinds"])
        )

      on_disk_all_kinds =
        MapSet.new(
          (on_disk["slashes"] |> Map.values() |> Enum.map(& &1["kind"])) ++
            Map.keys(on_disk["internal_kinds"])
        )

      missing_in_generated = MapSet.difference(on_disk_all_kinds, generated_all_kinds)

      # Allow a documented short-list of legacy orphan kinds whose only
      # presence in the on-disk yaml is as hand-rolled aliases for kinds
      # that ALSO exist under their canonical name. These are noise — when
      # the yaml becomes derived state in Phase 4 they fall out.
      legacy_orphans = MapSet.new(["grant", "revoke", "session_new_surface", "session_share_surface"])

      assert MapSet.subset?(missing_in_generated, legacy_orphans),
             "kinds present on disk but missing from generator (and not in legacy_orphans allowlist): " <>
               inspect(MapSet.difference(missing_in_generated, legacy_orphans))
    end
  end
end
