defmodule Mix.Tasks.Esr.GenCommandDocsTest do
  @moduledoc """
  Phase 4 (2026-05-09): tests for the `mix esr.gen_command_docs` emitter.
  """

  use ExUnit.Case, async: true

  alias Mix.Tasks.Esr.GenCommandDocs

  describe "emit_commands_md/0" do
    test "starts with the AUTOGENERATED banner" do
      md = GenCommandDocs.emit_commands_md()
      assert md =~ "<!-- AUTOGENERATED — DO NOT EDIT BY HAND."
      assert md =~ "Source: command_meta/0"
      assert md =~ "mix esr.gen_command_docs"
      assert md =~ "mix esr.check_command_docs"
    end

    test "contains the standard category headings" do
      md = GenCommandDocs.emit_commands_md()
      # Categories declared via `category` in DSL blocks. At least these
      # two should appear (Workspace + Sessions are core surfaces).
      assert md =~ "## Workspace"
      assert md =~ "## Sessions"
    end

    test "includes sample command kinds" do
      md = GenCommandDocs.emit_commands_md()
      # workspace_new is the canary command for the DSL migration.
      assert md =~ "### `workspace_new`"
      # help is the bare meta command.
      assert md =~ "### `help`"
      # reload is an internal-only kind.
      assert md =~ "### `reload`"
    end

    test "renders slash + args + bindings for a known command" do
      md = GenCommandDocs.emit_commands_md()
      # Find the workspace_new section and assert its key fields render.
      assert md =~ "/workspace:new"
      assert md =~ "Esr.Commands.Workspace.New"
    end

    test "two consecutive emits produce identical output" do
      a = GenCommandDocs.emit_commands_md()
      b = GenCommandDocs.emit_commands_md()
      assert a == b
    end
  end

  describe "emit_errors_md/0" do
    test "starts with the AUTOGENERATED banner" do
      md = GenCommandDocs.emit_errors_md()
      assert md =~ "<!-- AUTOGENERATED — DO NOT EDIT BY HAND."
      assert md =~ "Source: command_meta/0"
      assert md =~ "mix esr.gen_command_docs"
    end

    test "renders a markdown table header" do
      md = GenCommandDocs.emit_errors_md()
      assert md =~ "| type | kind | message |"
      assert md =~ "|------|------|---------|"
    end

    test "includes well-known error codes" do
      md = GenCommandDocs.emit_errors_md()
      # `invalid_args` is declared by virtually every command — must appear.
      assert md =~ "`invalid_args`"
      # `name_exists` is declared by Esr.Commands.Workspace.New.
      assert md =~ "`name_exists`"
    end

    test "two consecutive emits produce identical output" do
      a = GenCommandDocs.emit_errors_md()
      b = GenCommandDocs.emit_errors_md()
      assert a == b
    end
  end
end
