defmodule Mix.Tasks.Esr.GenBundleDocsTest do
  @moduledoc """
  Phase 8 (2026-05-10): tests for the `mix esr.gen_bundle_docs` mix task.

  Spec: `docs/superpowers/specs/2026-05-10-session-template-and-channel.md`
  Phase 8.
  """

  use ExUnit.Case, async: true

  alias Mix.Tasks.Esr.GenBundleDocs

  @bundles_root Path.expand("../../../lib/esr/bundles", __DIR__)

  describe "emit/0" do
    test "produces non-empty markdown with the AUTOGENERATED banner" do
      output = GenBundleDocs.emit()

      assert is_binary(output)
      assert output =~ "AUTOGENERATED — DO NOT EDIT BY HAND"
      assert output =~ "ESR Bundle / SessionTemplate Reference"
    end

    test "lists the in-tree feishu-cc bundle (lighthouse bundle)" do
      output = GenBundleDocs.emit()

      assert output =~ "## `feishu-cc`"
      assert output =~ "**version:** `0.1.0`"
      assert output =~ "**source:** `bundle (feishu-cc)`"
    end

    test "renders feishu-cc's dependency on feishu + claude_code plugins" do
      output = GenBundleDocs.emit()

      assert output =~ "plugins: `feishu`, `claude_code`"
    end

    test "renders feishu-cc's channel aliases + kinds" do
      output = GenBundleDocs.emit()

      assert output =~ "alias `in` → kind `feishu.chat_proxy`"
      assert output =~ "alias `cc_mcp` → kind `claude_code.mcp_stdio`"
    end

    test "renders feishu-cc's agent kind + consumes" do
      output = GenBundleDocs.emit()

      assert output =~ "kind `claude_code.cc`"
      assert output =~ "consumes `cc_mcp`"
    end

    test "renders feishu-cc's flow inbound + outbound" do
      output = GenBundleDocs.emit()

      assert output =~ "inbound:"
      assert output =~ "`in.text`"
      assert output =~ "outbound:"
      assert output =~ "sink `in.send`"
    end
  end

  describe "emit_from_dir/1" do
    test "renders an empty-state message for an empty directory" do
      tmp = Path.join(System.tmp_dir!(), "esr_gen_bundle_docs_empty_#{System.unique_integer([:positive])}")
      File.mkdir_p!(tmp)

      try do
        output = GenBundleDocs.emit_from_dir(tmp)

        assert output =~ "AUTOGENERATED"
        assert output =~ "_No bundles registered"
      after
        File.rm_rf!(tmp)
      end
    end

    test "skips directories missing manifest.yaml or template.yaml" do
      tmp = Path.join(System.tmp_dir!(), "esr_gen_bundle_docs_partial_#{System.unique_integer([:positive])}")
      File.mkdir_p!(Path.join(tmp, "no-manifest"))
      File.mkdir_p!(Path.join(tmp, "no-template"))
      File.write!(Path.join([tmp, "no-template", "manifest.yaml"]), """
      schema_version: 1
      name: no-template
      version: 0.1.0
      description: missing template
      dependencies:
        plugins: []
        bundles: []
      """)

      try do
        # Should not crash; should emit empty-bundles or skip both.
        # Capture Mix output to keep test silent.
        output =
          ExUnit.CaptureIO.capture_io(:stderr, fn ->
            send(self(), {:emitted, GenBundleDocs.emit_from_dir(tmp)})
          end)

        assert_receive {:emitted, emitted}
        # Both bundles should have been skipped — report emits empty.
        assert emitted =~ "No bundles registered"
        # Skip log lines reach :stderr via Mix.shell().error. Either form
        # is acceptable; we just want to confirm the task didn't raise.
        _ = output
      after
        File.rm_rf!(tmp)
      end
    end

    test "matches the in-tree bundles root when explicitly passed" do
      from_default = GenBundleDocs.emit()
      from_explicit = GenBundleDocs.emit_from_dir(@bundles_root)

      assert from_default == from_explicit
    end
  end
end
