defmodule Mix.Tasks.Esr.CheckCommandDocsTest do
  @moduledoc """
  Phase 4 (2026-05-09): tests for the `mix esr.check_command_docs` CI gate.
  """

  use ExUnit.Case, async: true

  alias Mix.Tasks.Esr.CheckCommandDocs

  describe "check/0" do
    test "returns :ok against the freshly-regenerated on-disk artifacts" do
      # The Phase 4 commit baseline regenerates slash-routes.default.yaml
      # + docs/grammar/{commands,errors}.md. Right after that baseline
      # the check_command_docs gate must pass.
      assert :ok = CheckCommandDocs.check()
    end
  end

  describe "strip_banner/1" do
    test "strips a leading `# ...` yaml banner block" do
      content = """
      # AUTOGENERATED — DO NOT EDIT BY HAND.
      # Source: command_meta/0.
      # Regenerate: mix esr.gen_slash_routes
      ---
      schema_version: 1
      """

      assert CheckCommandDocs.strip_banner(content) =~ "schema_version: 1"
      refute CheckCommandDocs.strip_banner(content) =~ "AUTOGENERATED"
    end

    test "strips a leading `<!-- ... -->` HTML-comment banner block" do
      content = """
      <!-- AUTOGENERATED — DO NOT EDIT BY HAND.
           Source: command_meta/0. -->

      # ESR Command Reference
      Body line.
      """

      stripped = CheckCommandDocs.strip_banner(content)
      assert stripped =~ "# ESR Command Reference"
      refute stripped =~ "AUTOGENERATED"
    end

    test "is a no-op on content with no banner" do
      content = "schema_version: 1\nslashes:\n  /foo: bar\n"
      assert CheckCommandDocs.strip_banner(content) == String.trim_leading(content)
    end
  end

  describe "verify_banner!/2" do
    test "returns :ok when the AUTOGENERATED marker is present" do
      content = "# AUTOGENERATED — DO NOT EDIT BY HAND.\n# More.\n---\nfoo: 1\n"
      assert :ok = CheckCommandDocs.verify_banner!(content, "/tmp/example.yaml")
    end

    test "raises when the banner is missing" do
      content = "schema_version: 1\nslashes:\n  /help: ...\n"

      assert_raise RuntimeError, ~r/missing AUTOGENERATED banner/, fn ->
        CheckCommandDocs.verify_banner!(content, "/tmp/tampered.yaml")
      end
    end

    test "raises with the path included in the message" do
      content = "no banner here"

      assert_raise RuntimeError, ~r{/some/specific/path\.md}, fn ->
        CheckCommandDocs.verify_banner!(content, "/some/specific/path.md")
      end
    end
  end
end
