defmodule EsrWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :esr

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_esr_key",
    signing_salt: "6G9b8HdB",
    same_site: "Lax"
  ]

  # PR-23: AttachSocket for browser xterm.js terminal attach. Replaces
  # the PR-22 LiveView path; raw Phoenix.Channel avoids the DOM-diffing
  # render jitter LiveView introduced.
  socket "/attach_socket", EsrWeb.AttachSocket,
    websocket: true,
    longpoll: false

  # Adapter WebSocket — Python adapter processes join
  # adapter:<name>/<instance_id> topics here (PRD 01 F09, spec §7.1).
  socket "/adapter_hub/socket", EsrWeb.AdapterSocket,
    websocket: true,
    longpoll: false

  # Handler WebSocket — Python handler workers join
  # handler:<module>/<worker_id> topics here (PRD 01 F12, spec §7.1).
  socket "/handler_hub/socket", EsrWeb.HandlerSocket,
    websocket: true,
    longpoll: false

  # MCP bridge WebSocket — esr-channel Python processes join
  # cli:channel/<session_id> topics here (PRD v0.2 §3.2).
  socket "/channel/socket", EsrWeb.ChannelSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :esr,
    gzip: not code_reloading?,
    only: EsrWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug EsrWeb.Router
end
