defmodule EsrWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :esr

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_esr_key",
    signing_salt: "6G9b8HdB",
    same_site: "Lax"
  ]

  # PR-24: raw binary WebSocket for browser xterm.js terminal attach.
  # PR-23's Phoenix.Channel transport JSON-encoded every PTY chunk, which
  # mangled ANSI ESC bytes and any 0x80-0xff payload — caused garbled
  # xterm.js render AND blocked claude (its boot-time DA1 / XTVERSION
  # queries never received valid replies through the JSON round-trip).
  # `EsrWeb.PtySocket` skips Phoenix.Channel and pushes raw binary
  # frames; matches ttyd's wire protocol shape.
  socket "/attach_socket", EsrWeb.PtySocket,
    websocket: [path: "/websocket", serializer: [], check_origin: false],
    longpoll: false

  # Adapter WebSocket — Python adapter processes join
  # adapter:<name>/<instance_id> topics here (PRD 01 F09, spec §7.1).
  socket "/adapter_hub/socket", EsrWeb.AdapterSocket,
    websocket: true,
    longpoll: false

  # Handler WebSocket — Python handler workers join
  # handler:<module>/<worker_id> topics here (PRD 01 F12, spec §7.1).
  socket "/handler_hub/socket", EsrWeb.HandlerSocket,
    websocket: true,
    longpoll: false

  # MCP bridge WebSocket — esr-channel Python processes join
  # cli:channel/<session_id> topics here (PRD v0.2 §3.2).
  socket "/channel/socket", EsrWeb.ChannelSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :esr,
    gzip: not code_reloading?,
    only: EsrWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug EsrWeb.Router
end
