import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# PR-22: ESR_HTTP_BIND env lets operator open the dev endpoint to the
# Tailnet (e.g. ESR_HTTP_BIND=0.0.0.0). Default loopback for safety.
http_bind =
  case System.get_env("ESR_HTTP_BIND") do
    nil -> {127, 0, 0, 1}
    "0.0.0.0" -> {0, 0, 0, 0}
    "::0" -> {0, 0, 0, 0, 0, 0, 0, 0}
    other ->
      other
      |> String.split(".")
      |> Enum.map(&String.to_integer/1)
      |> List.to_tuple()
  end

config :esr, EsrWeb.Endpoint,
  http: [ip: http_bind, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "KOdrsW/zedLNm8KEHDUojb3QkxZEkwnN5l0J/xKaVI9y0gfvzFIqRy9b+Fk0ce8h",
  # esbuild as a Phoenix watcher: rebuild priv/static/assets/app.js
  # whenever assets/js/* changes, with --watch for incremental rebuilds.
  # Pre-PR-24: empty watchers meant the bundle was built once (manually
  # or in mix.exs deps fetch) and stayed stale across dev edits — operators
  # restarted esrd and didn't see their JS changes until they ran
  # `mix esbuild default` by hand. The watcher entry here closes that gap.
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :esr, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
