defmodule Esr.Capabilities.Supervisor do

  @behaviour Esr.Role.OTP
  use Supervisor
  require Logger

  def start_link(opts), do: Supervisor.start_link(__MODULE__, opts, name: __MODULE__)

  @impl true
  def init(opts) do
    path = Keyword.get(opts, :path, default_path())
    dump_path = Path.join(Path.dirname(path), "permissions_registry.json")

    maybe_bootstrap_file(path)

    children = [
      Esr.Permissions.Registry,
      # Bootstrap must sit between Registry and Watcher so declared
      # permissions exist before FileLoader.validate/1 checks them.
      # `dump_path:` tells Bootstrap to write a JSON snapshot of the
      # registry once registration completes — consumed by
      # `esr cap list` (py/src/esr/cli/cap.py).
      {Esr.Permissions.Bootstrap, dump_path: dump_path},
      Esr.Capabilities.Grants,
      {Esr.Capabilities.Watcher, path: path}
    ]

    Supervisor.init(children, strategy: :rest_for_one)
  end

  defp default_path do
    Esr.Paths.capabilities_yaml()
  end

  # First-run bootstrap (capabilities spec §9.1): if the capabilities
  # file is missing AND ESR_BOOTSTRAP_PRINCIPAL_ID is set, write a seed
  # file granting that principal the admin wildcard. Lane A (CAP-5)
  # would otherwise default-deny every user on a fresh install.
  defp maybe_bootstrap_file(path) do
    with false <- File.exists?(path),
         bootstrap_id when is_binary(bootstrap_id) and bootstrap_id != "" <-
           System.get_env("ESR_BOOTSTRAP_PRINCIPAL_ID") do
      write_bootstrap_file(path, bootstrap_id)
    else
      _ -> :ok
    end
  end

  defp write_bootstrap_file(path, bootstrap_id) do
    content = """
    # Auto-generated by ESR first-run bootstrap.
    # ESR_BOOTSTRAP_PRINCIPAL_ID=#{bootstrap_id} was set and no
    # capabilities.yaml existed. Edit freely — changes hot-reload.

    principals:
      - id: #{bootstrap_id}
        kind: feishu_user
        note: bootstrap admin
        capabilities: ["*"]
    """

    with :ok <- File.mkdir_p(Path.dirname(path)),
         :ok <- File.write(path, content) do
      Logger.info("capabilities: bootstrapped #{bootstrap_id} as admin at #{path}")
      :ok
    else
      {:error, reason} ->
        Logger.warning(
          "capabilities: bootstrap write failed (#{inspect(reason)}); continuing without seed file"
        )

        :ok
    end
  end
end
