defmodule Esr.Peers.PtyProcess do
  @moduledoc """
  Generic PTY-backed peer (PR-22, 2026-05-01). Owns one OS process
  spawned via erlexec's `:pty` wrapper. Fans raw stdout chunks to
  Phoenix.PubSub topic `"pty:<session_id>"` for `EsrWeb.AttachLive`
  subscribers; accepts stdin via the public `write/2` and SIGWINCH via
  `resize/3`.

  Replaces `Esr.Peers.TmuxProcess`. The tmux control-mode protocol layer
  is gone; claude's TUI runs directly under erlexec's PTY.

  cc_process is **not** a PubSub subscriber here — the conversation path
  is cc_mcp → `cli:channel/<sid>`. PtyProcess only serves the operator-
  facing browser attach.

  ## Process structure

  - `start_link/1` starts `__MODULE__.OSProcessWorker` (generated by the
    `use Esr.OSProcess` macro). The worker holds the GenServer mailbox.
  - `init/1` runs inside the worker and registers under
    `Esr.PeerRegistry` with the binary actor_id `"pty:<sid>"` so
    `EsrWeb.AttachLive` can find this peer to forward stdin/resize.
  - `on_raw_stdout/2` (new optional `Esr.OSProcess` callback) fires
    BEFORE line-splitting, broadcasting raw bytes so ANSI escapes
    spanning chunk boundaries reach xterm.js intact.
  - `handle_downstream(:rewire_siblings, state)` runs the PR-21ω' rewire
    inlined here (no separate `PeerRewire` module).
  - `on_terminate/1` broadcasts a bare `:pty_closed` so attached
    LiveViews can render a "session ended" overlay.
  """

  require Logger

  @behaviour Esr.Role.State

  use Esr.Peer.Stateful
  use Esr.OSProcess, kind: :pty, wrapper: :pty

  alias Phoenix.PubSub

  # ------------------------------------------------------------------
  # Boot
  # ------------------------------------------------------------------

  def start_link(args) do
    args = Map.put_new(args, :subscriber, self())
    GenServer.start_link(__MODULE__.OSProcessWorker, args, name: name_for(args))
  end

  def child_spec(args) do
    %{
      id: __MODULE__,
      start: {__MODULE__, :start_link, [args]},
      type: :worker,
      restart: :transient,
      shutdown: 5_000
    }
  end

  @impl Esr.Peer
  def spawn_args(params) do
    name = "esr_pty_#{:erlang.unique_integer([:positive])}"

    %{
      session_name: name,
      dir: Esr.Peer.get_param(params, :dir) || "/tmp",
      session_id: Esr.Peer.get_param(params, :session_id),
      workspace_name: Esr.Peer.get_param(params, :workspace_name),
      chat_id: Esr.Peer.get_param(params, :chat_id),
      app_id: Esr.Peer.get_param(params, :app_id),
      start_cmd: Esr.Peer.get_param(params, :start_cmd)
    }
  end

  # ------------------------------------------------------------------
  # Public API (called from EsrWeb.AttachLive event handlers)
  # ------------------------------------------------------------------

  @doc "Forward keystrokes from xterm.js to the wrapped process's stdin."
  @spec write(String.t(), iodata()) :: :ok | {:error, term()}
  def write(sid, data) when is_binary(sid) do
    case Esr.PeerRegistry.lookup("pty:" <> sid) do
      {:ok, worker_pid} ->
        __MODULE__.OSProcessWorker.write_stdin(worker_pid, data)

      :error ->
        {:error, :no_pty_for_session}
    end
  end

  @doc "Forward window-size change from xterm.js (SIGWINCH)."
  @spec resize(String.t(), pos_integer(), pos_integer()) :: :ok | {:error, term()}
  def resize(sid, cols, rows)
      when is_binary(sid) and is_integer(cols) and is_integer(rows) and cols > 0 and rows > 0 do
    case Esr.PeerRegistry.lookup("pty:" <> sid) do
      {:ok, worker_pid} -> GenServer.cast(worker_pid, {:winsz, cols, rows})
      :error -> {:error, :no_pty_for_session}
    end
  end

  # ------------------------------------------------------------------
  # Peer init — registers in PeerRegistry, schedules rewire + trust
  # confirmation timers (gated for test env)
  # ------------------------------------------------------------------

  def init(%{session_name: _, dir: _} = args) do
    state = %{
      session_name: args.session_name,
      dir: args.dir,
      subscribers: [args[:subscriber] || self()],
      neighbors: Map.get(args, :neighbors, []),
      session_id: Map.get(args, :session_id),
      workspace_name: Map.get(args, :workspace_name),
      chat_id: Map.get(args, :chat_id),
      app_id: Map.get(args, :app_id),
      start_cmd: Map.get(args, :start_cmd)
    }

    sid = state.session_id

    # Register so AttachLive can find this peer by sid. Best-effort —
    # in unit tests we may run without a registered PeerRegistry; the
    # rest of the peer still works without registration.
    if is_binary(sid) and sid != "" do
      _ =
        try do
          Esr.PeerRegistry.register("pty:" <> sid, self())
        catch
          _, _ -> :error
        end
    end

    # PR-21ω' deferred rewire: must NOT call back into peers_sup
    # synchronously from init (deadlock). 50ms gives DynamicSupervisor
    # time to ack this child's start_child. Gated like TmuxProcess via
    # tmux_force_claude_launch (the same env flag controls whether
    # we're in a real session or a unit-test isolation).
    if is_binary(sid) and sid != "" and
         Application.get_env(:esr, :tmux_force_claude_launch, Mix.env() != :test) do
      Process.send_after(self(), :rewire_siblings, 50)
    end

    {:ok, state}
  end

  # T12a auto-confirm dropped in PR-22 live test: pre-PR-22 TmuxProcess
  # used `tmux send-keys ["1", :enter]` whose key events were absorbed
  # by claude's trust dialogs (no-op when no dialog showing). In PR-22's
  # raw-PTY world, `1\r` lands as plain stdin and shows up as user
  # input post-dialog — leaked "1"s into the conversation. Solution:
  # drop the auto-confirm entirely; CLAUDE_FLAGS in esr-cc.sh already
  # includes `--permission-mode bypassPermissions` +
  # `--dangerously-load-development-channels`, so the trust dialog
  # doesn't appear in the first place.

  # ------------------------------------------------------------------
  # OSProcess lifecycle hooks (signatures match os_process.ex callbacks)
  # ------------------------------------------------------------------

  @impl Esr.OSProcess
  def os_cmd(state) do
    cmd = state.start_cmd || default_start_cmd()
    # erlexec accepts a single command string; bash interprets it.
    ["bash", "-c", cmd]
  end

  @impl Esr.OSProcess
  def os_env(state) do
    case Map.get(state, :session_id) do
      sid when is_binary(sid) and sid != "" ->
        ws = Map.get(state, :workspace_name) || "default"
        chat_id = Map.get(state, :chat_id) || ""
        app_id = Map.get(state, :app_id) || ""

        chat_ids_json =
          Jason.encode!([%{chat_id: chat_id, app_id: app_id, kind: "feishu"}])

        [
          {"ESR_SESSION_ID", sid},
          {"ESR_WORKSPACE", ws},
          {"ESR_CHAT_IDS", chat_ids_json},
          {"ESR_ESRD_URL", channel_ws_url()}
        ]

      _ ->
        []
    end
  end

  @impl Esr.OSProcess
  # PR-22 raw-stdout hook — fires BEFORE line-splitting, so xterm.js
  # gets ANSI escape sequences intact across chunk boundaries.
  def on_raw_stdout(data, %{session_id: sid}) when is_binary(sid) and sid != "" do
    PubSub.broadcast(EsrWeb.PubSub, "pty:" <> sid, {:pty_stdout, data})
    :ok
  end

  def on_raw_stdout(_data, _state), do: :ok

  @impl Esr.OSProcess
  # PR-21ω'' carryover: any process exit (even 0) triggers peers
  # DynamicSupervisor's :transient restart so a fresh peer + claude
  # come back. PR-21ω' rewire patches siblings via :pty_process key.
  def on_os_exit(0, _state), do: {:stop, :pty_died_unexpectedly}
  def on_os_exit(status, _state), do: {:stop, {:pty_crashed, status}}

  @impl Esr.OSProcess
  # 1-arg per Esr.OSProcess @callback. No reason available; broadcast
  # bare :pty_closed so AttachLive can render the "session ended" overlay.
  def on_terminate(state) do
    case Map.get(state, :session_id) do
      sid when is_binary(sid) and sid != "" ->
        PubSub.broadcast(EsrWeb.PubSub, "pty:" <> sid, :pty_closed)

      _ ->
        :ok
    end

    :ok
  end

  # ------------------------------------------------------------------
  # Peer.Stateful — upstream events (line-split stdout) are no-ops
  # here; raw bytes are handled in on_raw_stdout/2 above.
  # ------------------------------------------------------------------

  @impl Esr.Peer.Stateful
  def handle_upstream(_msg, state), do: {:forward, [], state}

  # ------------------------------------------------------------------
  # Peer.Stateful — downstream events arrive when init's send_after
  # delivers messages (rewire, trust-confirm) or when sibling peers
  # send us commands.
  # ------------------------------------------------------------------

  @impl Esr.Peer.Stateful
  def handle_downstream(:rewire_siblings, state) do
    rewire_session_siblings(state)
    {:forward, [], state}
  end

  def handle_downstream(_msg, state), do: {:forward, [], state}

  # ------------------------------------------------------------------
  # Sibling rewire — verbatim port from tmux_process.ex (PR-21ω') with
  # the neighbor key flipped to :pty_process. Public for the rewire
  # test in Phase 4.
  # ------------------------------------------------------------------

  @doc false
  def rewire_session_siblings(%{session_id: sid}) when is_binary(sid) and sid != "" do
    peers_sup_via = {:via, Registry, {Esr.Session.Registry, {:peers_sup, sid}}}

    case GenServer.whereis(peers_sup_via) do
      nil ->
        :ok

      sup_pid ->
        my_pid = self()

        sup_pid
        |> DynamicSupervisor.which_children()
        |> Enum.each(fn
          {_id, child_pid, _type, _modules} when is_pid(child_pid) and child_pid != my_pid ->
            patch_neighbor_in_state(child_pid, :pty_process, my_pid)

          _ ->
            :ok
        end)
    end
  rescue
    _ -> :ok
  catch
    :exit, _ -> :ok
  end

  def rewire_session_siblings(_state), do: :ok

  defp patch_neighbor_in_state(pid, name, new_pid) do
    _ =
      :sys.replace_state(pid, fn
        %{parent: _, state: inner} = ws when is_map(inner) ->
          %{ws | state: %{inner | neighbors: Keyword.put(inner.neighbors, name, new_pid)}}

        %{neighbors: nb} = s when is_list(nb) ->
          %{s | neighbors: Keyword.put(nb, name, new_pid)}

        other ->
          other
      end)

    :ok
  rescue
    _ -> :ok
  catch
    :exit, _ -> :ok
  end

  # ------------------------------------------------------------------
  # Helpers
  # ------------------------------------------------------------------

  defp name_for(%{session_name: n}), do: String.to_atom("esr_pty_#{n}")

  defp default_start_cmd do
    Path.join([Application.app_dir(:esr), "..", "..", "..", "scripts", "esr-cc.sh"])
    |> Path.expand()
  end

  # Returns the esrd base WebSocket URL for cc_mcp's ESR_ESRD_URL env.
  # cc_mcp's ws_client.py appends `/channel/socket/websocket?vsn=2.0.0`
  # itself — we must return JUST the base (ws://host:port), no path.
  defp channel_ws_url do
    case Application.get_env(:esr, EsrWeb.Endpoint) do
      nil ->
        "ws://localhost:4001"

      cfg ->
        url = Keyword.get(cfg, :url, [])
        host = Keyword.get(url, :host, "localhost")
        port = Keyword.get(url, :port) || Keyword.get(cfg, :http, [])[:port] || 4001
        "ws://#{host}:#{port}"
    end
  end
end
