"""Walk the `esr` click CLI tree and dump every group/command's
--help output to a markdown reference. PR-19 2026-04-28.

Run: `uv run --project py python scripts/gen_cli_reference.py > docs/cli-reference.md`
or via `scripts/gen-docs.sh`. Manual run — checked into git so reviewers
can see CLI surface drift in PR diffs without standing up a venv.

Strategy: use click's own context machinery to get formatted help text
(stable layout matching what operators see). Walks groups recursively
so future nested subgroups get picked up automatically.
"""
from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path

# Add py/src to path so we can import esr.cli.main without depending on
# the project being installed.
_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT / "py" / "src"))

import click

from esr.cli.main import cli


def _format_help(cmd: click.Command, ctx: click.Context) -> str:
    formatter = ctx.make_formatter()
    cmd.format_help(ctx, formatter)
    return formatter.getvalue().rstrip()


def _walk(cmd: click.Command, parent_path: list[str], lines: list[str]) -> None:
    """Render `cmd` (and any subcommands) into `lines` as markdown."""
    full_name = " ".join(parent_path + [cmd.name]) if cmd.name else " ".join(parent_path)
    depth = len(parent_path) + 1
    heading = "#" * min(depth + 1, 6)

    lines.append(f"{heading} `{full_name}`")
    lines.append("")
    if cmd.help:
        # Click's `--help` already renders the docstring; we just want
        # the first paragraph as a one-line summary above the code block.
        summary = cmd.help.strip().split("\n\n", 1)[0].replace("\n", " ")
        lines.append(f"> {summary}")
        lines.append("")

    with click.Context(cmd, info_name=full_name) as ctx:
        lines.append("```")
        lines.append(_format_help(cmd, ctx))
        lines.append("```")
        lines.append("")

    if isinstance(cmd, click.Group):
        for sub_name in sorted(cmd.commands):
            _walk(cmd.commands[sub_name], parent_path + [cmd.name], lines)


def main() -> int:
    today = datetime.now().strftime("%Y-%m-%d")
    lines: list[str] = [
        "# ESR CLI reference",
        "",
        f"_Auto-generated by `scripts/gen_cli_reference.py` on {today}._",
        "_Don't hand-edit — modify the click docstrings in `py/src/esr/cli/`",
        "and re-run `bash scripts/gen-docs.sh`._",
        "",
        "---",
        "",
    ]
    _walk(cli, [], lines)
    sys.stdout.write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
