"""Parse `runtime/lib/esr_web/cli_channel.ex` for `dispatch/2` topic
clauses and the comment block immediately preceding each one. Render
as markdown — the runtime side of PR-19's CLI doc auto-gen.

Why parse instead of running `mix docs`: ExDoc renders module/function
docs but `dispatch/2` is one function with many clauses, and ExDoc
doesn't surface the "which topic does this clause handle" angle that
operators actually care about. Lightweight regex scan beats getting
ExDoc's output to the right shape.

Run: `uv run --project py python scripts/gen_runtime_channel_reference.py
       > docs/runtime-channel-reference.md`
or via `scripts/gen-docs.sh`.
"""
from __future__ import annotations

import re
import sys
from datetime import datetime
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
_TARGET = _REPO_ROOT / "runtime" / "lib" / "esr_web" / "cli_channel.ex"

# Match a `def dispatch("topic_pattern", ...)` line. The topic pattern
# can be a literal string or a binary-pattern (`"prefix:" <> name`).
# Capture group 1: the bareword topic literal or binary-pattern source.
_DISPATCH_RE = re.compile(
    r'^\s*def\s+dispatch\(\s*"([^"]+)"(?:\s*<>\s*([A-Za-z_][A-Za-z0-9_]*))?',
    re.MULTILINE,
)


def _extract_preceding_comment_block(lines: list[str], def_line_idx: int) -> str:
    """Walk backwards from the def line collecting `# ...` comment
    lines (skipping blank lines that interrupt). Returns the joined
    comment text with leading `# ` stripped, or empty string if no
    block was found.
    """
    block: list[str] = []
    i = def_line_idx - 1
    while i >= 0:
        line = lines[i].rstrip()
        stripped = line.lstrip()
        if stripped.startswith("#"):
            block.append(stripped[1:].lstrip())
        elif stripped == "":
            # Blank line terminates the block walking backwards once
            # we've already collected something; keep scanning if not.
            if block:
                break
        else:
            break
        i -= 1
    return "\n".join(reversed(block)).strip()


def main() -> int:
    if not _TARGET.exists():
        print(f"error: {_TARGET} not found", file=sys.stderr)
        return 1

    text = _TARGET.read_text()
    lines = text.split("\n")

    today = datetime.now().strftime("%Y-%m-%d")
    out: list[str] = [
        "# ESR runtime channel reference (`cli:` topics)",
        "",
        f"_Auto-generated by `scripts/gen_runtime_channel_reference.py` on {today}._",
        "_Source: `runtime/lib/esr_web/cli_channel.ex`. Don't hand-edit —",
        "modify the dispatch comments and re-run `bash scripts/gen-docs.sh`._",
        "",
        "Each section below documents one `dispatch/2` clause: the topic",
        "operators or sidecars hit, the payload it accepts, and what it",
        "does. Catch-all clauses (`_payload`) are listed with empty payload.",
        "",
        "---",
        "",
    ]

    seen_topics: set[str] = set()

    for match in _DISPATCH_RE.finditer(text):
        topic = match.group(1)
        suffix_var = match.group(2)
        full_topic = f"{topic}<{suffix_var}>" if suffix_var else topic

        if full_topic in seen_topics:
            # Duplicate (catch-all) — skip; first occurrence already documented.
            continue
        seen_topics.add(full_topic)

        # Find the line index for this def to extract the comment above.
        line_no = text[: match.start()].count("\n")
        comment = _extract_preceding_comment_block(lines, line_no)

        out.append(f"## `{full_topic}`")
        out.append("")
        if comment:
            out.append(comment)
            out.append("")
        else:
            out.append("_(No documentation comment.)_")
            out.append("")
        out.append("---")
        out.append("")

    sys.stdout.write("\n".join(out) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
