#!/usr/bin/env bash
# promote-dev-to-main.sh — opens a fast-forward promotion PR
# (head=dev, base=main). Fills the PR description with every commit
# on dev since main. Merge is a fast-forward (`gh pr merge --rebase`).
#
# See docs/dev-flow.md for the full git flow.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

# Sanity: are we in the primary worktree (the one that tracks main)?
# `git branch --show-current` is empty for detached HEAD; non-empty
# branch is fine — we don't need to be on main.

git fetch origin --quiet

# Compare dev vs main on origin (not local — local may be stale).
COMMITS_AHEAD="$(git rev-list --count origin/main..origin/dev)"
if [ "$COMMITS_AHEAD" = "0" ]; then
  echo "origin/dev is not ahead of origin/main; nothing to promote."
  exit 0
fi

echo "Promoting $COMMITS_AHEAD commit(s) from origin/dev to origin/main:"
git --no-pager log --oneline origin/main..origin/dev

# Build the PR body: changelog of every commit since main.
BODY_FILE="$(mktemp)"
trap 'rm -f "$BODY_FILE"' EXIT

cat >"$BODY_FILE" <<EOF
## Promotion: dev → main

Fast-forward merge. Each commit below was already merged to \`dev\` via
its own feature PR; this promotion PR is zero-diff and exists only to
move \`main\` forward to \`origin/dev\` HEAD.

### Commits being promoted

EOF
git --no-pager log --oneline origin/main..origin/dev >>"$BODY_FILE"

cat >>"$BODY_FILE" <<EOF


### Merge instructions

\`\`\`
gh pr merge <#> --rebase --delete-branch=false
\`\`\`

\`--rebase\` performs a fast-forward (no merge commit). \`--delete-branch=false\`
keeps \`dev\` alive — it's a permanent branch, not a feature branch.

After merge, sync the primary worktree:
\`\`\`
( cd ~/Workspace/esr && git pull --ff-only origin main )
launchctl kickstart -k gui/\$(id -u)/com.ezagent.esrd
\`\`\`

🤖 Auto-generated by scripts/promote-dev-to-main.sh
EOF

PR_TITLE="Promote dev → main: $COMMITS_AHEAD commit(s)"

gh pr create \
  --base main \
  --head dev \
  --title "$PR_TITLE" \
  --body-file "$BODY_FILE"
