#!/usr/bin/env python3
"""E2E capabilities scenario harness — 7 tracks (CAP-A..CAP-G).

This is the **component-level** E2E for ESR's capability-based access
control subsystem. It validates every enforcement seam individually
(CapabilitiesChecker, FeishuAdapter Lane A gate, `esr cap` CLI, file
loader log-line contract, runtime Lane B witness test) against
realistic fixtures, without requiring a running esrd / mock_feishu /
mock_cc.

A fully-orchestrated live E2E (spawn esrd, drive WebSocket frames
through the Phoenix channel, assert teardown-safe log lines) is a v2
improvement — the component-level harness catches every regression a
live run would surface at the enforcement points, with none of the
orchestration flakiness.

Usage::

    cd /Users/h2oslabs/Workspace/esr/.worktrees/esr-capabilities
    uv run --project py python scripts/scenarios/e2e_capabilities.py

Exit 0 with ``"7 tracks PASSED"`` iff every track asserts cleanly;
exit 1 on the first failure, printing the failing track + details.

Maps to: ``docs/superpowers/tests/e2e-capabilities.md`` (track-by-track
human spec); implementation plan Phase CAP-9 Task 15.
"""
from __future__ import annotations

import os
import shutil
import sys
import tempfile
import traceback
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

# Make `esr` + `esr_feishu` importable when running from a checkout.
_REPO = Path(__file__).resolve().parents[2]
for sub in ("py/src", "adapters/feishu/src"):
    path = _REPO / sub
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))


# --- Result plumbing ----------------------------------------------------


@dataclass
class TrackResult:
    """One track's verdict after all its assertions run."""

    name: str
    passed: bool
    details: str = ""

    def line(self) -> str:
        status = "PASS" if self.passed else "FAIL"
        return f"[{status}] Track {self.name}: {self.details}"


def _assert(cond: bool, msg: str) -> None:
    """Raise AssertionError if ``cond`` is false. Bare assert would be
    stripped under ``python -O``; this form stays loud.
    """
    if not cond:
        raise AssertionError(msg)


# --- Shared fixtures ----------------------------------------------------


def _write_caps(path: Path, principals: list[dict[str, Any]]) -> None:
    """Write a minimal ``capabilities.yaml`` for one track."""
    import yaml

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump({"principals": principals}, sort_keys=False))


def _write_workspaces(path: Path, workspaces: list[dict[str, Any]]) -> None:
    """Write a minimal ``workspaces.yaml`` for one track.

    Schema mirrors what ``esr.workspaces.read_workspaces`` expects —
    a top-level ``workspaces`` mapping keyed by workspace name. Each
    entry value is the row (cwd / start_cmd / role / chats / env).
    Callers pass a list of entries with a ``name`` key for convenience;
    we pivot it into the dict shape the reader wants.
    """
    import yaml

    by_name: dict[str, dict[str, Any]] = {}
    for row in workspaces:
        r = dict(row)
        name = r.pop("name")
        by_name[name] = r
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump({"workspaces": by_name}, sort_keys=False))


def _bump_mtime(path: Path, by: float = 1.5) -> None:
    """Advance the file's mtime by ``by`` seconds so mtime-gated reloads
    see the change even on coarse-resolution filesystems.
    """
    st = path.stat()
    os.utime(path, (st.st_atime, st.st_mtime + by))


# --- Track CAP-A — Admin flow (bootstrap principal) ---------------------


def track_cap_a(tmp: Path) -> TrackResult:
    """Bootstrap `ou_admin` via the same shape ``Esr.Capabilities.Supervisor``
    writes; verify both Lane A and Lane B allow admin on `coord-prod`.
    """
    from esr.capabilities import CapabilitiesChecker

    try:
        esrd_home = tmp / "cap-a"
        caps = esrd_home / "default" / "capabilities.yaml"

        # The BEAM supervisor writes this shape; we write it directly
        # because the harness runs in Python and the supervisor can't
        # be exercised without starting the OTP app.
        caps.parent.mkdir(parents=True, exist_ok=True)
        caps.write_text(
            "# Auto-generated by ESR first-run bootstrap.\n"
            "# ESR_BOOTSTRAP_PRINCIPAL_ID=ou_admin was set and no\n"
            "# capabilities.yaml existed. Edit freely — changes hot-reload.\n"
            "\n"
            "principals:\n"
            "  - id: ou_admin\n"
            "    kind: feishu_user\n"
            "    note: bootstrap admin\n"
            '    capabilities: ["*"]\n'
        )

        # A-1: seed file has admin wildcard
        content = caps.read_text()
        _assert("id: ou_admin" in content, "seed file missing ou_admin")
        _assert('["*"]' in content, "seed file missing admin wildcard")

        checker = CapabilitiesChecker(caps)

        # A-2: Lane A (msg.send) allowed
        _assert(
            checker.has("ou_admin", "workspace:coord-prod/msg.send") is True,
            "admin denied msg.send",
        )

        # A-3: Lane B (session.create) allowed
        _assert(
            checker.has("ou_admin", "workspace:coord-prod/session.create") is True,
            "admin denied session.create",
        )

        # A-4: envelope carries principal_id + workspace_name at top level
        from esr.ipc.envelope import make_event

        env = make_event(
            source="esr://localhost/adapter/feishu/test",
            event_type="msg_received",
            args={"content": "hi admin"},
            principal_id="ou_admin",
            workspace_name="coord-prod",
        )
        _assert(env["principal_id"] == "ou_admin", "envelope principal_id mismatch")
        _assert(
            env["workspace_name"] == "coord-prod",
            "envelope workspace_name mismatch",
        )

        return TrackResult("CAP-A", True, "admin bootstrap + both lanes allow")
    except AssertionError as e:
        return TrackResult("CAP-A", False, f"assertion: {e}")
    except Exception:
        return TrackResult("CAP-A", False, f"exception:\n{traceback.format_exc()}")


# --- Track CAP-B — Regular user flow ------------------------------------


def track_cap_b(tmp: Path) -> TrackResult:
    """`ou_alice` holds msg.send + session.create for `coord-prod`; both
    Lane A (adapter `_is_authorized`) and Lane B (checker for
    session.create) allow.
    """
    from esr_feishu.adapter import FeishuAdapter

    from esr.adapter import AdapterConfig
    from esr.capabilities import CapabilitiesChecker

    try:
        esrd_home = tmp / "cap-b"
        caps = esrd_home / "default" / "capabilities.yaml"
        ws = esrd_home / "default" / "workspaces.yaml"

        _write_caps(
            caps,
            [
                {
                    "id": "ou_alice",
                    "kind": "feishu_user",
                    "capabilities": [
                        "workspace:coord-prod/msg.send",
                        "workspace:coord-prod/session.create",
                    ],
                }
            ],
        )
        _write_workspaces(
            ws,
            [
                {
                    "name": "coord-prod",
                    "cwd": "/tmp/coord-prod",
                    "start_cmd": "esr-cc",
                    "role": "ops",
                    "chats": [
                        {
                            "chat_id": "oc_alice_chat",
                            "app_id": "cli_prod",
                            "kind": "dm",
                        }
                    ],
                }
            ],
        )

        checker = CapabilitiesChecker(caps)
        _assert(
            checker.has("ou_alice", "workspace:coord-prod/msg.send") is True,
            "B-1 Lane A check failed",
        )
        _assert(
            checker.has("ou_alice", "workspace:coord-prod/session.create") is True,
            "B-2 Lane B session.create check failed",
        )

        adapter = FeishuAdapter(
            actor_id="feishu-app:test",
            config=AdapterConfig(
                {
                    "app_id": "cli_prod",
                    "app_secret": "s",
                    "workspaces_path": str(ws),
                    "capabilities_path": str(caps),
                }
            ),
        )
        _assert(
            adapter._is_authorized("ou_alice", "oc_alice_chat") is True,
            "B-3 adapter _is_authorized denied a valid principal",
        )

        return TrackResult("CAP-B", True, "scoped user passes Lane A + Lane B")
    except AssertionError as e:
        return TrackResult("CAP-B", False, f"assertion: {e}")
    except Exception:
        return TrackResult("CAP-B", False, f"exception:\n{traceback.format_exc()}")


# --- Track CAP-C — Lane A deny + rate limit ------------------------------


def track_cap_c(tmp: Path) -> TrackResult:
    """`ou_rando` has no grants; adapter denies and sends exactly one deny
    DM within the 10-minute window. Cycling the monotonic clock past the
    window allows a second DM.
    """
    from unittest.mock import patch

    from esr_feishu.adapter import FeishuAdapter

    from esr.adapter import AdapterConfig

    try:
        esrd_home = tmp / "cap-c"
        caps = esrd_home / "default" / "capabilities.yaml"
        ws = esrd_home / "default" / "workspaces.yaml"

        _write_caps(caps, [])  # no one is granted
        _write_workspaces(
            ws,
            [
                {
                    "name": "coord-prod",
                    "cwd": "/tmp/coord-prod",
                    "start_cmd": "esr-cc",
                    "role": "ops",
                    "chats": [
                        {
                            "chat_id": "oc_rando_chat",
                            "app_id": "cli_prod",
                            "kind": "dm",
                        }
                    ],
                }
            ],
        )

        adapter = FeishuAdapter(
            actor_id="feishu-app:test",
            config=AdapterConfig(
                {
                    "app_id": "cli_prod",
                    "app_secret": "s",
                    "workspaces_path": str(ws),
                    "capabilities_path": str(caps),
                }
            ),
        )

        # C-1: deny
        _assert(
            adapter._is_authorized("ou_rando", "oc_rando_chat") is False,
            "C-1 ungranted user should be denied",
        )

        # Drive the rate-limit gate directly, using a patched monotonic
        # clock — the existing test_lane_a.py test suite uses the same
        # technique (see ``test_deny_rate_limit_expires_after_window``)
        # because pinning a 600 s boundary with real time would stall CI.
        clock = [1000.0]
        with patch("esr_feishu.adapter.time.monotonic", lambda: clock[0]):
            # C-2: first DM allowed
            _assert(
                adapter._should_send_deny("ou_rando") is True,
                "C-2 first deny DM should fire",
            )
            # C-3: second DM within window is silent
            clock[0] = 1200.0  # +200s, still < 600s window
            _assert(
                adapter._should_send_deny("ou_rando") is False,
                "C-3 second deny DM within window should be silent",
            )
            # C-4: after window, deny fires again
            clock[0] = 1601.0  # +601s from t=1000 → outside 600s window
            _assert(
                adapter._should_send_deny("ou_rando") is True,
                "C-4 deny DM should fire again after window elapses",
            )

        return TrackResult(
            "CAP-C", True, "Lane A deny + 10-min rate-limit window honoured"
        )
    except AssertionError as e:
        return TrackResult("CAP-C", False, f"assertion: {e}")
    except Exception:
        return TrackResult("CAP-C", False, f"exception:\n{traceback.format_exc()}")


# --- Track CAP-D — Lane B deny (tool_invoke unauthorized) ---------------


def track_cap_d(tmp: Path) -> TrackResult:
    """`ou_reader` holds msg.send but not session.create; Lane A passes
    but Lane B denies. Runtime witness: the BEAM test ``peer_server_lane_b_test.exs``
    proves the deny branch emits an unauthorized tool_result; this
    harness asserts the witness file exists with the correct literals.
    """
    from esr.capabilities import CapabilitiesChecker

    try:
        esrd_home = tmp / "cap-d"
        caps = esrd_home / "default" / "capabilities.yaml"
        _write_caps(
            caps,
            [
                {
                    "id": "ou_reader",
                    "kind": "feishu_user",
                    "capabilities": ["workspace:coord-prod/msg.send"],
                }
            ],
        )

        checker = CapabilitiesChecker(caps)

        # D-1: Lane A passes
        _assert(
            checker.has("ou_reader", "workspace:coord-prod/msg.send") is True,
            "D-1 reader should pass Lane A",
        )
        # D-2: Lane B (session.create) denies
        _assert(
            checker.has("ou_reader", "workspace:coord-prod/session.create") is False,
            "D-2 reader should be denied session.create",
        )

        # D-3: runtime witness test exists with required literals
        witness = _REPO / "runtime" / "test" / "esr" / "peer_server_lane_b_test.exs"
        _assert(witness.exists(), f"D-3 witness file missing: {witness}")
        witness_text = witness.read_text()
        _assert(
            "unauthorized" in witness_text,
            "D-3 witness file missing 'unauthorized' literal",
        )
        _assert(
            "required_perm" in witness_text,
            "D-3 witness file missing 'required_perm' literal",
        )

        # D-4: handler-facing reply shape documented by the witness
        _assert(
            'result["ok"] == false' in witness_text
            or "result[\"ok\"] == false" in witness_text,
            "D-4 witness file doesn't assert tool_result.ok == false",
        )

        return TrackResult(
            "CAP-D",
            True,
            "Lane B denies session.create; witness test validated",
        )
    except AssertionError as e:
        return TrackResult("CAP-D", False, f"assertion: {e}")
    except Exception:
        return TrackResult("CAP-D", False, f"exception:\n{traceback.format_exc()}")


# --- Track CAP-E — Workspace scoping ------------------------------------


def track_cap_e(tmp: Path) -> TrackResult:
    """`ou_dev` holds `workspace:proj-a/*` — denies in `proj-b`."""
    from esr_feishu.adapter import FeishuAdapter

    from esr.adapter import AdapterConfig
    from esr.capabilities import CapabilitiesChecker

    try:
        esrd_home = tmp / "cap-e"
        caps = esrd_home / "default" / "capabilities.yaml"
        ws = esrd_home / "default" / "workspaces.yaml"

        _write_caps(
            caps,
            [
                {
                    "id": "ou_dev",
                    "kind": "feishu_user",
                    "capabilities": ["workspace:proj-a/*"],
                }
            ],
        )
        _write_workspaces(
            ws,
            [
                {
                    "name": "proj-a",
                    "cwd": "/tmp/proj-a",
                    "start_cmd": "esr-cc",
                    "role": "dev",
                    "chats": [
                        {"chat_id": "oc_a", "app_id": "cli_prod", "kind": "dm"}
                    ],
                },
                {
                    "name": "proj-b",
                    "cwd": "/tmp/proj-b",
                    "start_cmd": "esr-cc",
                    "role": "dev",
                    "chats": [
                        {"chat_id": "oc_b", "app_id": "cli_prod", "kind": "dm"}
                    ],
                },
            ],
        )

        checker = CapabilitiesChecker(caps)

        _assert(
            checker.has("ou_dev", "workspace:proj-a/msg.send") is True,
            "E-1 same-workspace msg.send should pass",
        )
        _assert(
            checker.has("ou_dev", "workspace:proj-a/session.create") is True,
            "E-2 same-workspace session.create should pass (perm wildcard)",
        )
        _assert(
            checker.has("ou_dev", "workspace:proj-b/msg.send") is False,
            "E-3 cross-workspace should deny",
        )

        adapter = FeishuAdapter(
            actor_id="feishu-app:test",
            config=AdapterConfig(
                {
                    "app_id": "cli_prod",
                    "app_secret": "s",
                    "workspaces_path": str(ws),
                    "capabilities_path": str(caps),
                }
            ),
        )
        _assert(
            adapter._is_authorized("ou_dev", "oc_b") is False,
            "E-4 adapter _is_authorized cross-workspace should deny",
        )

        return TrackResult(
            "CAP-E", True, "workspace prefix matches literally — no cross-leak"
        )
    except AssertionError as e:
        return TrackResult("CAP-E", False, f"assertion: {e}")
    except Exception:
        return TrackResult("CAP-E", False, f"exception:\n{traceback.format_exc()}")


# --- Track CAP-F — Hot reload -------------------------------------------


def track_cap_f(tmp: Path) -> TrackResult:
    """`esr cap grant ou_bob ...` rewrites the file; the next `has()` call
    picks it up via mtime-gated reload — no restart.
    """
    from click.testing import CliRunner

    from esr.capabilities import CapabilitiesChecker
    from esr.cli.cap import cap as cap_group

    try:
        esrd_home = tmp / "cap-f"
        caps = esrd_home / "default" / "capabilities.yaml"

        # Seed with `ou_prior` so the file starts non-empty.
        _write_caps(
            caps,
            [
                {
                    "id": "ou_prior",
                    "kind": "feishu_user",
                    "capabilities": ["workspace:coord-prod/msg.send"],
                }
            ],
        )

        checker = CapabilitiesChecker(caps)
        # F-1: pre-grant deny
        _assert(
            checker.has("ou_bob", "workspace:coord-prod/msg.send") is False,
            "F-1 bob should start denied",
        )

        # F-2: invoke the CLI with ESRD_HOME pointing at our tmp dir
        runner = CliRunner()
        result = runner.invoke(
            cap_group,
            ["grant", "ou_bob", "workspace:coord-prod/msg.send"],
            env={"ESRD_HOME": str(esrd_home)},
        )
        _assert(
            result.exit_code == 0,
            f"F-2 esr cap grant failed: exit={result.exit_code}, out={result.output!r}",
        )
        _assert(
            "ou_bob" in result.output,
            f"F-2 esr cap grant output missing ou_bob: {result.output!r}",
        )

        # F-3: file updated on disk
        content = caps.read_text()
        _assert(
            "ou_bob" in content and "workspace:coord-prod/msg.send" in content,
            "F-3 capabilities.yaml missing new grant",
        )

        # F-4: post-grant allow (bump mtime to ensure reload picks it up)
        _bump_mtime(caps)
        _assert(
            checker.has("ou_bob", "workspace:coord-prod/msg.send") is True,
            "F-4 hot reload did not pick up new grant",
        )

        return TrackResult(
            "CAP-F", True, "grant hot-reloaded via mtime-gated reread"
        )
    except AssertionError as e:
        return TrackResult("CAP-F", False, f"assertion: {e}")
    except Exception:
        return TrackResult("CAP-F", False, f"exception:\n{traceback.format_exc()}")


# --- Track CAP-G — File corruption resilience ---------------------------


def track_cap_g(tmp: Path) -> TrackResult:
    """Malformed YAML → checker keeps previous snapshot, runtime logs
    ``keeping previous snapshot``. Fixing the file loads the new one.
    """
    from esr.capabilities import CapabilitiesChecker

    try:
        esrd_home = tmp / "cap-g"
        caps = esrd_home / "default" / "capabilities.yaml"

        # Start with a valid file + warm the checker's snapshot
        _write_caps(
            caps,
            [
                {
                    "id": "ou_prior",
                    "kind": "feishu_user",
                    "capabilities": ["workspace:coord-prod/msg.send"],
                }
            ],
        )
        checker = CapabilitiesChecker(caps)
        _assert(
            checker.has("ou_prior", "workspace:coord-prod/msg.send") is True,
            "G-1 pre-corruption baseline failed",
        )

        # Corrupt the file with an unterminated flow collection —
        # same shape as the Elixir file_loader_test uses
        caps.write_text("principals:\n  - id: x,\n  capabilities: [workspace:a/msg.send,\n")
        _bump_mtime(caps)

        # G-2: previous snapshot survives
        _assert(
            checker.has("ou_prior", "workspace:coord-prod/msg.send") is True,
            "G-2 corruption dropped the previous snapshot",
        )

        # Fix the file with a new principal
        _write_caps(
            caps,
            [
                {
                    "id": "ou_fix",
                    "kind": "feishu_user",
                    "capabilities": ["workspace:coord-prod/msg.send"],
                }
            ],
        )
        _bump_mtime(caps, by=2.5)

        # G-3: new snapshot loads
        _assert(
            checker.has("ou_fix", "workspace:coord-prod/msg.send") is True,
            "G-3 fix did not load new snapshot",
        )

        # G-4: runtime-side log-line contract present
        file_loader = (
            _REPO / "runtime" / "lib" / "esr" / "capabilities" / "file_loader.ex"
        )
        _assert(file_loader.exists(), f"G-4 file_loader.ex not found: {file_loader}")
        _assert(
            "keeping previous snapshot" in file_loader.read_text(),
            "G-4 runtime file_loader missing log-line contract",
        )

        return TrackResult(
            "CAP-G",
            True,
            "corrupt file keeps prior snapshot; fix loads new; runtime log-line present",
        )
    except AssertionError as e:
        return TrackResult("CAP-G", False, f"assertion: {e}")
    except Exception:
        return TrackResult("CAP-G", False, f"exception:\n{traceback.format_exc()}")


# --- Runner -------------------------------------------------------------


TRACKS: list[tuple[str, Callable[[Path], TrackResult]]] = [
    ("CAP-A", track_cap_a),
    ("CAP-B", track_cap_b),
    ("CAP-C", track_cap_c),
    ("CAP-D", track_cap_d),
    ("CAP-E", track_cap_e),
    ("CAP-F", track_cap_f),
    ("CAP-G", track_cap_g),
]


def main() -> int:
    """Run every track; exit 0 iff all pass."""
    print("ESR capabilities E2E — 7 tracks")
    print("=" * 60)

    tmp = Path(tempfile.mkdtemp(prefix="esr-cap-e2e-"))
    results: list[TrackResult] = []
    try:
        for _name, fn in TRACKS:
            result = fn(tmp)
            results.append(result)
            print(result.line())
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    print("=" * 60)
    passed = sum(1 for r in results if r.passed)
    if passed == len(TRACKS):
        print(f"{passed}/{len(TRACKS)} tracks PASSED")
        print(f"{passed} steps PASSED")
        return 0

    failed = [r for r in results if not r.passed]
    print(f"{passed}/{len(TRACKS)} tracks passed; {len(failed)} failed")
    for r in failed:
        print(f"  - {r.name}: {r.details}")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
