#!/usr/bin/env python3
"""E2E capabilities scenario harness — 4 tracks (CAP-A, CAP-E, CAP-F, CAP-G).

This is the **component-level** E2E for ESR's capability-based access
control subsystem. Validates the enforcement seams that survive the
Lane A drop (2026-04-26):

- CAP-A: admin/bootstrap principal capability resolution
- CAP-E: workspace-scoped pattern matching (no cross-workspace leak)
- CAP-F: hot reload via FileLoader mtime gate
- CAP-G: file-corruption resilience (bad yaml → keep prior snapshot)

CAP-B / CAP-C / CAP-D were removed alongside Lane A. They exercised
`adapter._is_authorized` / `_should_send_deny` / "Lane A passes,
Lane B denies" cross-lane semantics — none of which exist anymore.
Lane B's gate + deny-DM dispatch are covered by ExUnit tests at:
  runtime/test/esr/peer_server_lane_b_deny_dispatch_test.exs
  runtime/test/esr/peers/feishu_app_adapter_deny_dm_test.exs

Usage::

    uv run --project py python scripts/scenarios/e2e_capabilities.py

Exit 0 iff every surviving track asserts cleanly; exit 1 on first
failure with track + details.

Maps to: ``docs/superpowers/tests/e2e-capabilities.md`` (track-by-track
human spec; updated post Lane A drop).
"""
from __future__ import annotations

import os
import shutil
import sys
import tempfile
import traceback
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

# Make `esr` + `esr_feishu` importable when running from a checkout.
_REPO = Path(__file__).resolve().parents[2]
for sub in ("py/src", "adapters/feishu/src"):
    path = _REPO / sub
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))


# --- Result plumbing ----------------------------------------------------


@dataclass
class TrackResult:
    """One track's verdict after all its assertions run."""

    name: str
    passed: bool
    details: str = ""

    def line(self) -> str:
        status = "PASS" if self.passed else "FAIL"
        return f"[{status}] Track {self.name}: {self.details}"


def _assert(cond: bool, msg: str) -> None:
    """Raise AssertionError if ``cond`` is false. Bare assert would be
    stripped under ``python -O``; this form stays loud.
    """
    if not cond:
        raise AssertionError(msg)


# --- Shared fixtures ----------------------------------------------------


def _write_caps(path: Path, principals: list[dict[str, Any]]) -> None:
    """Write a minimal ``capabilities.yaml`` for one track."""
    import yaml

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump({"principals": principals}, sort_keys=False))


def _write_workspaces(path: Path, workspaces: list[dict[str, Any]]) -> None:
    """Write a minimal ``workspaces.yaml`` for one track.

    Schema mirrors what ``esr.workspaces.read_workspaces`` expects —
    a top-level ``workspaces`` mapping keyed by workspace name. Each
    entry value is the row (cwd / start_cmd / role / chats / env).
    Callers pass a list of entries with a ``name`` key for convenience;
    we pivot it into the dict shape the reader wants.
    """
    import yaml

    by_name: dict[str, dict[str, Any]] = {}
    for row in workspaces:
        r = dict(row)
        name = r.pop("name")
        by_name[name] = r
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump({"workspaces": by_name}, sort_keys=False))


def _bump_mtime(path: Path, by: float = 1.5) -> None:
    """Advance the file's mtime by ``by`` seconds so mtime-gated reloads
    see the change even on coarse-resolution filesystems.
    """
    st = path.stat()
    os.utime(path, (st.st_atime, st.st_mtime + by))


# --- Track CAP-A — Admin flow (bootstrap principal) ---------------------


def track_cap_a(tmp: Path) -> TrackResult:
    """Bootstrap `ou_admin` via the same shape ``Esr.Capabilities.Supervisor``
    writes; verify both Lane A and Lane B allow admin on `coord-prod`.
    """
    from esr.capabilities import CapabilitiesChecker

    try:
        esrd_home = tmp / "cap-a"
        caps = esrd_home / "default" / "capabilities.yaml"

        # The BEAM supervisor writes this shape; we write it directly
        # because the harness runs in Python and the supervisor can't
        # be exercised without starting the OTP app.
        caps.parent.mkdir(parents=True, exist_ok=True)
        caps.write_text(
            "# Auto-generated by ESR first-run bootstrap.\n"
            "# ESR_BOOTSTRAP_PRINCIPAL_ID=ou_admin was set and no\n"
            "# capabilities.yaml existed. Edit freely — changes hot-reload.\n"
            "\n"
            "principals:\n"
            "  - id: ou_admin\n"
            "    kind: feishu_user\n"
            "    note: bootstrap admin\n"
            '    capabilities: ["*"]\n'
        )

        # A-1: seed file has admin wildcard
        content = caps.read_text()
        _assert("id: ou_admin" in content, "seed file missing ou_admin")
        _assert('["*"]' in content, "seed file missing admin wildcard")

        checker = CapabilitiesChecker(caps)

        # A-2: Lane A (msg.send) allowed
        _assert(
            checker.has("ou_admin", "workspace:coord-prod/msg.send") is True,
            "admin denied msg.send",
        )

        # A-3: Lane B (session.create) allowed
        _assert(
            checker.has("ou_admin", "workspace:coord-prod/session.create") is True,
            "admin denied session.create",
        )

        # A-4: envelope carries principal_id + workspace_name at top level
        from esr.ipc.envelope import make_event

        env = make_event(
            source="esr://localhost/adapter/feishu/test",
            event_type="msg_received",
            args={"content": "hi admin"},
            principal_id="ou_admin",
            workspace_name="coord-prod",
        )
        _assert(env["principal_id"] == "ou_admin", "envelope principal_id mismatch")
        _assert(
            env["workspace_name"] == "coord-prod",
            "envelope workspace_name mismatch",
        )

        return TrackResult("CAP-A", True, "admin bootstrap + both lanes allow")
    except AssertionError as e:
        return TrackResult("CAP-A", False, f"assertion: {e}")
    except Exception:
        return TrackResult("CAP-A", False, f"exception:\n{traceback.format_exc()}")



# --- Track CAP-E — Workspace scoping ------------------------------------


def track_cap_e(tmp: Path) -> TrackResult:
    """`ou_dev` holds `workspace:proj-a/*` — denies in `proj-b`.

    Post-Lane-A drop (2026-04-26) this track only verifies the
    CapabilitiesChecker pattern matching that runs during yaml load
    + ``esr cap who-can`` resolution. The adapter-side `_is_authorized`
    assertion that lived here is gone — Lane B's gate at
    `peer_server.ex:236-274` is the same `Capabilities.has?/2` shape
    and is exercised by `peer_server_lane_b_deny_dispatch_test.exs`.
    """
    from esr.capabilities import CapabilitiesChecker

    try:
        esrd_home = tmp / "cap-e"
        caps = esrd_home / "default" / "capabilities.yaml"

        _write_caps(
            caps,
            [
                {
                    "id": "ou_dev",
                    "kind": "feishu_user",
                    "capabilities": ["workspace:proj-a/*"],
                }
            ],
        )

        checker = CapabilitiesChecker(caps)

        _assert(
            checker.has("ou_dev", "workspace:proj-a/msg.send") is True,
            "E-1 same-workspace msg.send should pass",
        )
        _assert(
            checker.has("ou_dev", "workspace:proj-a/session.create") is True,
            "E-2 same-workspace session.create should pass (perm wildcard)",
        )
        _assert(
            checker.has("ou_dev", "workspace:proj-b/msg.send") is False,
            "E-3 cross-workspace should deny",
        )

        return TrackResult(
            "CAP-E", True, "workspace prefix matches literally — no cross-leak"
        )
    except AssertionError as e:
        return TrackResult("CAP-E", False, f"assertion: {e}")
    except Exception:
        return TrackResult("CAP-E", False, f"exception:\n{traceback.format_exc()}")


# --- Track CAP-F — Hot reload -------------------------------------------


def track_cap_f(tmp: Path) -> TrackResult:
    """`esr cap grant ou_bob ...` rewrites the file; the next `has()` call
    picks it up via mtime-gated reload — no restart.
    """
    from click.testing import CliRunner

    from esr.capabilities import CapabilitiesChecker
    from esr.cli.cap import cap as cap_group

    try:
        esrd_home = tmp / "cap-f"
        caps = esrd_home / "default" / "capabilities.yaml"

        # Seed with `ou_prior` so the file starts non-empty.
        _write_caps(
            caps,
            [
                {
                    "id": "ou_prior",
                    "kind": "feishu_user",
                    "capabilities": ["workspace:coord-prod/msg.send"],
                }
            ],
        )

        checker = CapabilitiesChecker(caps)
        # F-1: pre-grant deny
        _assert(
            checker.has("ou_bob", "workspace:coord-prod/msg.send") is False,
            "F-1 bob should start denied",
        )

        # F-2: invoke the CLI with ESRD_HOME pointing at our tmp dir
        runner = CliRunner()
        result = runner.invoke(
            cap_group,
            ["grant", "ou_bob", "workspace:coord-prod/msg.send"],
            env={"ESRD_HOME": str(esrd_home)},
        )
        _assert(
            result.exit_code == 0,
            f"F-2 esr cap grant failed: exit={result.exit_code}, out={result.output!r}",
        )
        _assert(
            "ou_bob" in result.output,
            f"F-2 esr cap grant output missing ou_bob: {result.output!r}",
        )

        # F-3: file updated on disk
        content = caps.read_text()
        _assert(
            "ou_bob" in content and "workspace:coord-prod/msg.send" in content,
            "F-3 capabilities.yaml missing new grant",
        )

        # F-4: post-grant allow (bump mtime to ensure reload picks it up)
        _bump_mtime(caps)
        _assert(
            checker.has("ou_bob", "workspace:coord-prod/msg.send") is True,
            "F-4 hot reload did not pick up new grant",
        )

        return TrackResult(
            "CAP-F", True, "grant hot-reloaded via mtime-gated reread"
        )
    except AssertionError as e:
        return TrackResult("CAP-F", False, f"assertion: {e}")
    except Exception:
        return TrackResult("CAP-F", False, f"exception:\n{traceback.format_exc()}")


# --- Track CAP-G — File corruption resilience ---------------------------


def track_cap_g(tmp: Path) -> TrackResult:
    """Malformed YAML → checker keeps previous snapshot, runtime logs
    ``keeping previous snapshot``. Fixing the file loads the new one.
    """
    from esr.capabilities import CapabilitiesChecker

    try:
        esrd_home = tmp / "cap-g"
        caps = esrd_home / "default" / "capabilities.yaml"

        # Start with a valid file + warm the checker's snapshot
        _write_caps(
            caps,
            [
                {
                    "id": "ou_prior",
                    "kind": "feishu_user",
                    "capabilities": ["workspace:coord-prod/msg.send"],
                }
            ],
        )
        checker = CapabilitiesChecker(caps)
        _assert(
            checker.has("ou_prior", "workspace:coord-prod/msg.send") is True,
            "G-1 pre-corruption baseline failed",
        )

        # Corrupt the file with an unterminated flow collection —
        # same shape as the Elixir file_loader_test uses
        caps.write_text("principals:\n  - id: x,\n  capabilities: [workspace:a/msg.send,\n")
        _bump_mtime(caps)

        # G-2: previous snapshot survives
        _assert(
            checker.has("ou_prior", "workspace:coord-prod/msg.send") is True,
            "G-2 corruption dropped the previous snapshot",
        )

        # Fix the file with a new principal
        _write_caps(
            caps,
            [
                {
                    "id": "ou_fix",
                    "kind": "feishu_user",
                    "capabilities": ["workspace:coord-prod/msg.send"],
                }
            ],
        )
        _bump_mtime(caps, by=2.5)

        # G-3: new snapshot loads
        _assert(
            checker.has("ou_fix", "workspace:coord-prod/msg.send") is True,
            "G-3 fix did not load new snapshot",
        )

        # G-4: runtime-side log-line contract present
        file_loader = (
            _REPO / "runtime" / "lib" / "esr" / "capabilities" / "file_loader.ex"
        )
        _assert(file_loader.exists(), f"G-4 file_loader.ex not found: {file_loader}")
        _assert(
            "keeping previous snapshot" in file_loader.read_text(),
            "G-4 runtime file_loader missing log-line contract",
        )

        return TrackResult(
            "CAP-G",
            True,
            "corrupt file keeps prior snapshot; fix loads new; runtime log-line present",
        )
    except AssertionError as e:
        return TrackResult("CAP-G", False, f"assertion: {e}")
    except Exception:
        return TrackResult("CAP-G", False, f"exception:\n{traceback.format_exc()}")


# --- Runner -------------------------------------------------------------


TRACKS: list[tuple[str, Callable[[Path], TrackResult]]] = [
    ("CAP-A", track_cap_a),
    # CAP-B / CAP-C / CAP-D removed 2026-04-26 (Lane A drop) — they
    # exercised `_is_authorized` / `_should_send_deny` / dual-lane
    # divergence that no longer exist. Lane B's gate + deny-DM
    # dispatch are covered by:
    #   runtime/test/esr/peer_server_lane_b_deny_dispatch_test.exs
    #   runtime/test/esr/peers/feishu_app_adapter_deny_dm_test.exs
    ("CAP-E", track_cap_e),
    ("CAP-F", track_cap_f),
    ("CAP-G", track_cap_g),
]


def main() -> int:
    """Run every track; exit 0 iff all pass."""
    print(f"ESR capabilities E2E — {len(TRACKS)} tracks")
    print("=" * 60)

    tmp = Path(tempfile.mkdtemp(prefix="esr-cap-e2e-"))
    results: list[TrackResult] = []
    try:
        for _name, fn in TRACKS:
            result = fn(tmp)
            results.append(result)
            print(result.line())
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    print("=" * 60)
    passed = sum(1 for r in results if r.passed)
    if passed == len(TRACKS):
        print(f"{passed}/{len(TRACKS)} tracks PASSED")
        print(f"{passed} steps PASSED")
        return 0

    failed = [r for r in results if not r.passed]
    print(f"{passed}/{len(TRACKS)} tracks passed; {len(failed)} failed")
    for r in failed:
        print(f"  - {r.name}: {r.details}")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
