defmodule Mix.Tasks.Esr.GenSlashRoutes do
  @moduledoc """
  Emit `runtime/priv/slash-routes.default.yaml` from each command module's
  `command_meta/0` (the `Esr.Commands.Meta.Spec{}` returned by the DSL).

  Phase 4 (2026-05-09) of the unified-command-grammar migration. Before
  this task, the yaml was hand-edited and could drift from the DSL specs.
  After this task, the yaml is derived state — Phase 5 will wire
  `mix esr.check_command_docs` into CI as a drift gate.

  ## Usage

      mix esr.gen_slash_routes

  ## Module discovery

  Walks every loaded module under `Elixir.Esr.Commands.*` that exports
  `command_meta/0`. Each spec's `slash:` field decides the section:

    * `slash: :none` → emitted under `internal_kinds:` (kind-keyed)
    * `slash: "/<group>:<verb>"` → emitted under `slashes:` (slash-keyed)

  Output is deterministic — `Ymlr.document!/2` is called with
  `sort_maps: true`, and the slash / kind sections are sorted before
  emission.

  Plugin commands (under `Elixir.Esr.Plugins.<plugin>.Commands.*`) are
  intentionally NOT emitted into the base yaml. Each plugin ships its
  own `slash_routes:` block in `lib/esr/plugins/<plugin>/manifest.yaml`
  and that block is loaded as an overlay (Audit #6 / 2026-05-08-plugin-
  command-registration spec §5.3). Those plugin specs are still
  reachable via `command_meta/0` for documentation generation
  (`mix esr.gen_command_docs`) but never land in the base yaml.
  """

  use Mix.Task

  @shortdoc "Emit slash-routes.default.yaml from command_meta/0"

  @target_path "priv/slash-routes.default.yaml"

  @banner """
  # AUTOGENERATED — DO NOT EDIT BY HAND.
  # Source: command_meta/0 in each Esr.Commands.* / Esr.Plugins.*.Commands.* module.
  # Regenerate: mix esr.gen_slash_routes
  # Drift in this file fails CI via mix esr.check_command_docs.
  """

  @impl Mix.Task
  def run(_args) do
    Mix.Task.run("compile")
    # Load (don't start) the OTP app: we only need :application.get_key
    # to enumerate the module list + command_meta/0 callbacks at compile
    # time. Starting the full supervision tree boots the SlashRoute
    # Watcher which fails on CI Linux runners (no FSEvents/inotify path
    # at $ESRD_HOME). This task is read-only against compiled BEAM.
    Application.load(:esr)

    yaml = emit()
    path = Path.expand(@target_path, File.cwd!())
    File.write!(path, yaml)
    Mix.shell().info("wrote #{path} (#{byte_size(yaml)} bytes)")
    :ok
  end

  @doc """
  Pure function — emits the full yaml string (banner + Ymlr-encoded body).
  Used by `run/1` to write to disk and by `Mix.Tasks.Esr.CheckCommandDocs`
  to compare against the on-disk file.
  """
  @spec emit() :: String.t()
  def emit do
    specs = collect_specs()

    body = %{
      "schema_version" => 1,
      "slashes" => slashes_map(specs),
      "internal_kinds" => internal_kinds_map(specs)
    }

    # Indirect call via apply/3 — the BEAM has Ymlr loaded at runtime
    # (it's a runtime dep) but the compiler-time check warns when a Mix
    # task module references it directly because `mix compile` builds
    # this file before Ymlr is added to the build path. The runtime call
    # path is unaffected.
    yml = apply(Ymlr, :document!, [body, [sort_maps: true]])
    @banner <> yml
  end

  # ------------------------------------------------------------------
  # Module discovery
  # ------------------------------------------------------------------

  @doc """
  Collect every base-yaml command spec — modules under
  `Elixir.Esr.Commands.*` exporting `command_meta/0`. Plugin command
  modules are excluded; they ship via their plugin manifest overlay.
  """
  @spec collect_specs() :: [{module(), Esr.Commands.Meta.Spec.t()}]
  def collect_specs do
    {:ok, modules} = :application.get_key(:esr, :modules)

    modules
    |> Enum.filter(&base_command_module?/1)
    |> Enum.map(fn mod -> {mod, mod.command_meta()} end)
  end

  @doc """
  Collect every command spec including plugin command modules under
  `Elixir.Esr.Plugins.<plugin>.Commands.*`. Used by
  `Mix.Tasks.Esr.GenCommandDocs` (docs cover both base + plugin
  commands so operators see one unified reference).
  """
  @spec collect_all_specs() :: [{module(), Esr.Commands.Meta.Spec.t()}]
  def collect_all_specs do
    {:ok, modules} = :application.get_key(:esr, :modules)

    modules
    |> Enum.filter(&any_command_module?/1)
    |> Enum.map(fn mod -> {mod, mod.command_meta()} end)
  end

  defp base_command_module?(mod) do
    name = Atom.to_string(mod)

    String.starts_with?(name, "Elixir.Esr.Commands.") and
      command_meta_exported?(mod)
  end

  defp any_command_module?(mod) do
    name = Atom.to_string(mod)

    cond do
      String.starts_with?(name, "Elixir.Esr.Commands.") ->
        command_meta_exported?(mod)

      String.starts_with?(name, "Elixir.Esr.Plugins.") and
          String.contains?(name, ".Commands.") ->
        command_meta_exported?(mod)

      true ->
        false
    end
  end

  # `:application.get_key(:esr, :modules)` returns module ATOMS, but
  # they may not yet be code-loaded into the BEAM (especially plugin
  # modules — they're listed in :esr's app spec but lazily loaded). The
  # naked `function_exported?/3` check returns false on unloaded
  # modules; route through `Code.ensure_loaded?/1` first.
  defp command_meta_exported?(mod) do
    Code.ensure_loaded?(mod) and function_exported?(mod, :command_meta, 0)
  end

  # ------------------------------------------------------------------
  # slashes: section
  # ------------------------------------------------------------------

  defp slashes_map(specs) do
    specs
    |> Enum.reject(fn {_mod, %{slash: slash}} -> slash == :none end)
    |> Enum.map(fn {mod, spec} -> {spec.slash, slash_entry(mod, spec)} end)
    |> Map.new()
  end

  defp slash_entry(mod, spec) do
    %{
      "kind" => Atom.to_string(spec.kind),
      "permission" => spec.permission,
      "command_module" => module_name_string(mod),
      "requires_workspace_binding" => spec.requires_workspace_binding,
      "requires_user_binding" => spec.requires_user_binding,
      "category" => spec.category,
      "description" => spec.description,
      "args" => Enum.map(spec.args, &arg_entry/1)
    }
  end

  defp arg_entry(%Esr.Commands.Meta.Arg{name: name, required: required, default: default}) do
    base = %{
      "name" => Atom.to_string(name),
      "required" => required
    }

    case default do
      nil -> base
      value -> Map.put(base, "default", default_to_yaml(value))
    end
  end

  # YAML can't carry arbitrary Elixir terms — coerce booleans/atoms to
  # the same string forms the existing yaml uses (e.g. "false").
  defp default_to_yaml(true), do: "true"
  defp default_to_yaml(false), do: "false"
  defp default_to_yaml(value) when is_atom(value), do: Atom.to_string(value)
  defp default_to_yaml(value) when is_binary(value), do: value
  defp default_to_yaml(value), do: value

  # ------------------------------------------------------------------
  # internal_kinds: section
  # ------------------------------------------------------------------

  defp internal_kinds_map(specs) do
    specs
    |> Enum.filter(fn {_mod, %{slash: slash}} -> slash == :none end)
    |> Enum.map(fn {mod, spec} ->
      {Atom.to_string(spec.kind),
       %{
         "permission" => spec.permission,
         "command_module" => module_name_string(mod)
       }}
    end)
    |> Map.new()
  end

  # ------------------------------------------------------------------
  # Module name helpers
  # ------------------------------------------------------------------

  @doc false
  def module_name_string(mod) when is_atom(mod) do
    case Atom.to_string(mod) do
      "Elixir." <> rest -> rest
      other -> other
    end
  end
end
