defmodule Mix.Tasks.Esr.AuditSupervision do
  @moduledoc """
  Snapshot the live supervision tree at app boot and diff against
  `docs/notes/supervisor-inventory.md`. Non-empty diff exits 1 — CI
  gate that catches an accidental supervisor topology change.

  ## Usage

      mix esr.audit_supervision

      # Regenerate the baseline after an intentional topology change.
      # Use --write=PATH so Logger output to stdout doesn't pollute the
      # file; the task writes the snapshot directly via File.write/2.
      cd runtime && mix esr.audit_supervision --write=../docs/notes/supervisor-inventory.md

  ## Walked roots

  The task starts the app and snapshots every named supervisor in
  the supervision tree starting from a fixed root list. The recursion
  is shallow: each row records the supervisor's atom name + strategy
  + child IDs. Child supervisors get their own rows.

  PR-3 Task 3.10. Spec §4.9.
  """

  use Mix.Task

  @shortdoc "Snapshot supervision tree; diff against docs/notes/supervisor-inventory.md"

  @baseline_path "../docs/notes/supervisor-inventory.md"

  # Top-level roots to walk. Walking `Esr.Supervisor` reaches every
  # sub-supervisor transitively; the dedicated session/admin entries
  # here are listed so the snapshot pins their order even when
  # Esr.Supervisor's children list is reordered. Add new ones here
  # when the application gains a top-level supervisor; the diff will
  # fire and force a baseline refresh.
  @roots [
    Esr.Supervisor,
    Esr.Session.Supervisor,
    Esr.Session.LifecycleObservers,
    Esr.Session.Admin,
    Esr.Session.Admin.ChildrenSupervisor
  ]

  @impl Mix.Task
  def run(args) do
    Mix.Task.run("app.start")
    # Silence Logger for the snapshot — boot warnings (stale session
    # JSON skips, etc.) are noise that would pollute the baseline file
    # if redirected with `> docs/notes/supervisor-inventory.md`.
    Logger.configure(level: :error)

    snapshot = build_snapshot(@roots)

    cond do
      "--write" in args ->
        IO.puts(snapshot)
        :ok

      write_path = Enum.find_value(args, &write_path_from_arg/1) ->
        File.write!(write_path, snapshot)
        Mix.shell().info("audit_supervision: wrote snapshot to #{write_path}")
        :ok

      true ->
        baseline = read_baseline()

        if snapshot == baseline do
          Mix.shell().info(
            "audit_supervision: snapshot matches baseline (#{byte_size(snapshot)} bytes)"
          )

          :ok
        else
          Mix.shell().error("audit_supervision: DRIFT detected")
          Mix.shell().error("--- baseline (docs/notes/supervisor-inventory.md) ---")
          Mix.shell().error(baseline)
          Mix.shell().error("--- snapshot (live) ---")
          Mix.shell().error(snapshot)
          Mix.shell().error("--- end ---")
          Mix.shell().error("")

          Mix.shell().error(
            "If this drift is intentional, regenerate the baseline with:\n" <>
              "  cd runtime && mix esr.audit_supervision --write=../docs/notes/supervisor-inventory.md"
          )

          System.halt(1)
        end
    end
  end

  defp write_path_from_arg("--write=" <> path) when path != "", do: path
  defp write_path_from_arg(_), do: nil

  defp read_baseline do
    case File.read(@baseline_path) do
      {:ok, content} -> String.trim(content) <> "\n"
      {:error, _} -> ""
    end
  end

  defp build_snapshot(roots) do
    header = """
    # Supervisor inventory (auto-generated)

    Snapshot of every named supervisor reachable from the listed roots.
    Generated by `mix esr.audit_supervision --write`. Do not hand-edit —
    rerun the task to refresh.

    Each row: `<supervisor name> (<strategy>): [<child_id_1>, ...]`

    """

    rows =
      roots
      |> Enum.flat_map(&walk(&1, MapSet.new()))
      |> Enum.uniq()
      |> Enum.sort()

    header <> Enum.join(rows, "\n") <> "\n"
  end

  # Walk a supervisor (by atom name or pid), recursing into supervisor
  # children. `seen` tracks already-visited names so cycles don't recur.
  defp walk(name, seen) when is_atom(name) do
    case Process.whereis(name) do
      nil -> []
      pid -> walk_pid(name, pid, seen)
    end
  end

  defp walk(pid, seen) when is_pid(pid) do
    walk_pid(pid, pid, seen)
  end

  defp walk_pid(label, pid, seen) do
    label_str = inspect(label)

    if MapSet.member?(seen, label_str) do
      []
    else
      seen = MapSet.put(seen, label_str)

      case extract_supervisor_state(pid) do
        {:ok, strategy, children} ->
          row =
            "- `#{label_str}` (#{strategy}): " <>
              "[" <> Enum.map_join(children, ", ", &format_child/1) <> "]"

          # Recurse into supervisor children using the child id (a module
          # atom most of the time, which gives a readable inventory)
          # rather than the pid.
          subrows =
            children
            |> Enum.flat_map(fn {id, child_pid, type, _modules} ->
              cond do
                type == :supervisor and is_atom(id) and is_pid(child_pid) ->
                  walk(id, seen)

                type == :supervisor and is_pid(child_pid) ->
                  walk(child_pid, seen)

                true ->
                  []
              end
            end)

          [row | subrows]

        :error ->
          []
      end
    end
  end

  defp extract_supervisor_state(pid) do
    # Guard: a Supervisor.which_children/1 call to a GenServer that's
    # NOT a supervisor crashes the target. The supervisor behaviour
    # registers `'$initial_call'` with the dictionary; sniff it before
    # calling.
    if supervisor?(pid) do
      try do
        children = Supervisor.which_children(pid)
        strategy = strategy_of(pid)
        {:ok, strategy, children}
      catch
        :exit, _ -> :error
      end
    else
      :error
    end
  end

  defp supervisor?(pid) when is_pid(pid) do
    case Process.info(pid, :dictionary) do
      {:dictionary, dict} ->
        case Keyword.get(dict, :"$initial_call") do
          {:supervisor, _, _} -> true
          # Registry / DynamicSupervisor / etc. all start :supervisor.
          _ -> false
        end

      _ ->
        false
    end
  end

  defp supervisor?(_), do: false

  defp strategy_of(pid) do
    try do
      case :sys.get_state(pid, 500) do
        %{strategy: s} when is_atom(s) -> Atom.to_string(s)
        # Erlang :supervisor state is a tuple — sniff index 2 which is
        # the strategy atom in OTP 25+.
        state when is_tuple(state) ->
          case state do
            {:state, _, strategy, _, _, _, _, _, _, _, _, _} when is_atom(strategy) ->
              Atom.to_string(strategy)

            _ ->
              "unknown"
          end

        _ ->
          "unknown"
      end
    catch
      :exit, _ -> "unknown"
    end
  end

  defp format_child({id, child_pid, type, _modules}) do
    type_tag = if type == :supervisor, do: "sup", else: "worker"

    pid_tag =
      cond do
        is_pid(child_pid) and Process.alive?(child_pid) -> "alive"
        is_pid(child_pid) -> "dead"
        true -> Atom.to_string(child_pid)
      end

    "#{inspect(id)}:#{type_tag}:#{pid_tag}"
  end
end
