defmodule Mix.Tasks.Esr.GenCommandDocs do
  @moduledoc """
  Emit `docs/grammar/commands.md` + `docs/grammar/errors.md` from each
  command module's `command_meta/0`.

  Phase 4/6 of the unified-command-grammar migration. Companion to
  `mix esr.gen_slash_routes` — both share the same module-discovery
  + spec-walking infrastructure (in
  `Mix.Tasks.Esr.GenSlashRoutes.collect_all_specs/0`); this task
  consumes ALL specs (base + plugin) since the operator-facing
  reference should cover every command, regardless of whether it ships
  in the base yaml or a plugin overlay.

  ## Usage

      mix esr.gen_command_docs

  ## Output

    * `docs/grammar/commands.md` — every command grouped by category,
      with slash + args + description + kind + permission + binding
      flags + errors.
    * `docs/grammar/errors.md` — flat catalog of (type, kind, message)
      rows for the error inventory.

  Both files start with an HTML-comment AUTOGENERATED banner; the
  matching CI gate is `mix esr.check_command_docs`.
  """

  use Mix.Task

  @shortdoc "Emit docs/grammar/{commands,errors}.md from command_meta/0"

  @commands_path "docs/grammar/commands.md"
  @errors_path "docs/grammar/errors.md"

  @banner """
  <!-- AUTOGENERATED — DO NOT EDIT BY HAND.
       Source: command_meta/0 in each Esr.Commands.* module.
       Regenerate: mix esr.gen_command_docs
       Drift in this file fails CI via mix esr.check_command_docs. -->
  """

  @impl Mix.Task
  def run(_args) do
    Mix.Task.run("compile")
    # See esr.gen_slash_routes.ex for why we load (not start) the app.
    Application.load(:esr)

    repo_root = Path.expand("..", File.cwd!())
    cmd_path = Path.join(repo_root, @commands_path)
    err_path = Path.join(repo_root, @errors_path)

    File.mkdir_p!(Path.dirname(cmd_path))
    File.write!(cmd_path, emit_commands_md())
    File.write!(err_path, emit_errors_md())
    Mix.shell().info("wrote #{cmd_path}")
    Mix.shell().info("wrote #{err_path}")
    :ok
  end

  @doc """
  Pure function — returns the full markdown for `commands.md`.
  Deterministic: specs sorted by category then kind.
  """
  @spec emit_commands_md() :: String.t()
  def emit_commands_md do
    specs = Mix.Tasks.Esr.GenSlashRoutes.collect_all_specs()

    groups =
      specs
      |> Enum.sort_by(fn {_mod, s} -> {s.category, Atom.to_string(s.kind)} end)
      |> Enum.group_by(fn {_mod, s} -> s.category end)
      |> Enum.sort_by(fn {category, _} -> category end)

    intro = """
    # ESR Command Reference

    Generated from each command module's `command_meta/0` declaration. The
    canonical source is the DSL block under
    `Esr.Commands.*` and `Esr.Plugins.*.Commands.*`; do not edit this file
    directly.

    """

    body =
      Enum.map_join(groups, "\n", fn {category, items} ->
        rows =
          Enum.map_join(items, "\n", fn {mod, spec} ->
            render_command_entry(mod, spec)
          end)

        "## #{category}\n\n#{rows}\n"
      end)

    @banner <> "\n" <> intro <> body
  end

  @doc """
  Pure function — returns the full markdown for `errors.md`.
  Deterministic: rows sorted by (kind, code).
  """
  @spec emit_errors_md() :: String.t()
  def emit_errors_md do
    specs = Mix.Tasks.Esr.GenSlashRoutes.collect_all_specs()

    rows =
      specs
      |> Enum.flat_map(fn {_mod, spec} ->
        Enum.map(spec.errors, fn err ->
          %{
            type: Atom.to_string(err.code),
            kind: Atom.to_string(spec.kind),
            message: err.message || ""
          }
        end)
      end)
      |> Enum.sort_by(fn r -> {r.kind, r.type} end)

    intro = """
    # ESR Command Error Catalog

    Flat inventory of every `error` declaration across command modules.
    Generated from `command_meta/0`; do not edit directly.

    | type | kind | message |
    |------|------|---------|
    """

    table =
      Enum.map_join(rows, "\n", fn r ->
        "| `#{r.type}` | `#{r.kind}` | #{escape_table_cell(r.message)} |"
      end)

    @banner <> "\n" <> intro <> table <> "\n"
  end

  # ------------------------------------------------------------------
  # Internals
  # ------------------------------------------------------------------

  defp render_command_entry(mod, spec) do
    slash_line =
      case spec.slash do
        :none -> "_internal kind only — not slash-callable_"
        slash -> "**slash:** `#{slash}`"
      end

    args_section =
      case spec.args do
        [] -> "**args:** _none_"
        args -> "**args:**\n" <> Enum.map_join(args, "\n", &render_arg/1)
      end

    errors_section =
      case spec.errors do
        [] -> "**errors:** _none declared_"
        errs -> "**errors:**\n" <> Enum.map_join(errs, "\n", &render_error/1)
      end

    """
    ### `#{spec.kind}`

    #{slash_line}

    **module:** `#{Mix.Tasks.Esr.GenSlashRoutes.module_name_string(mod)}`

    **permission:** `#{format_perm(spec.permission)}`

    **bindings:** requires_user_binding=`#{spec.requires_user_binding}` requires_workspace_binding=`#{spec.requires_workspace_binding}`

    **description:** #{spec.description}

    #{args_section}

    #{errors_section}
    """
  end

  defp render_arg(%Esr.Commands.Meta.Arg{} = arg) do
    req = if arg.required, do: "required", else: "optional"
    default_str = if is_nil(arg.default), do: "", else: " default=`#{inspect(arg.default)}`"
    doc = if arg.doc, do: " — #{arg.doc}", else: ""
    "  - `#{arg.name}` (#{req})#{default_str}#{doc}"
  end

  defp render_error(%Esr.Commands.Meta.ErrorDecl{} = err) do
    msg = err.message || "_(no canonical message)_"
    "  - `#{err.code}` — #{msg}"
  end

  defp format_perm(nil), do: "null"
  defp format_perm(perm), do: perm

  defp escape_table_cell(""), do: "_(no canonical message)_"
  defp escape_table_cell(text) do
    text
    |> String.replace("|", "\\|")
    |> String.replace("\n", " ")
  end
end
