defmodule Mix.Tasks.Esr.GenBundleDocs do
  @moduledoc """
  Emit `docs/grammar/templates.md` from every in-tree bundle's
  `manifest.yaml` + `template.yaml`.

  Phase 8 of the SessionTemplate + Channel migration (spec
  `docs/superpowers/specs/2026-05-10-session-template-and-channel.md`).
  Mirrors `mix esr.gen_command_docs` for consistency: read static
  on-disk artifacts, render markdown with an AUTOGENERATED banner, write
  to `docs/grammar/`.

  ## Usage

      mix esr.gen_bundle_docs

  ## Output

  `docs/grammar/templates.md` — one section per bundle, listing:

    * name, version, description
    * source (`:bundle` for in-tree, `:operator` for `${ESRD_HOME}/<inst>/session_templates/`)
    * dependencies (plugins + bundles)
    * channels (alias + kind + config)
    * agents (kind + name + consumes)
    * flow (inbound + outbound)

  Output is deterministic — bundles sorted by name; channels / agents
  / flow entries kept in declaration order (matching the yaml authoring
  intent).

  ## Why static parse, not Registry walk

  The mix task runs against a clean checkout (CI or developer dev box);
  there's no esrd booted, so `Esr.Bundle.Registry.list_all/0` is empty.
  This task walks `runtime/lib/esr/bundles/*/` directly via
  `Esr.Bundle.Manifest.parse/1` + `Esr.SessionTemplate.Parser.parse/2`.
  Operator-shipped session_templates are NOT enumerated here — they're
  per-deployment artifacts, not source-tree artifacts.
  """

  use Mix.Task

  @shortdoc "Emit docs/grammar/templates.md from runtime/lib/esr/bundles/*/"

  @target_path "docs/grammar/templates.md"

  @banner """
  <!-- AUTOGENERATED — DO NOT EDIT BY HAND.
       Source: runtime/lib/esr/bundles/*/{manifest,template}.yaml.
       Regenerate: mix esr.gen_bundle_docs
       Drift in this file fails CI via mix esr.check_bundles. -->
  """

  @impl Mix.Task
  def run(_args) do
    Mix.Task.run("compile")
    Application.load(:esr)

    repo_root = Path.expand("..", File.cwd!())
    out_path = Path.join(repo_root, @target_path)

    File.mkdir_p!(Path.dirname(out_path))
    File.write!(out_path, emit())
    Mix.shell().info("wrote #{out_path}")
    :ok
  end

  @doc """
  Pure function — returns the full markdown for `templates.md`.
  Deterministic: bundles sorted by name.

  Resolves the bundles root via `Esr.Paths.bundles_dir/0` so the same
  resolution policy used by `Esr.Bundle.Loader.load_all/0` at boot is
  reused here (mix-run dev path: `runtime/lib/esr/bundles`).
  """
  @spec emit() :: String.t()
  def emit do
    emit_from_dir(Esr.Paths.bundles_dir())
  end

  @doc """
  Public for testing — emit markdown from any bundles root directory.
  """
  @spec emit_from_dir(Path.t()) :: String.t()
  def emit_from_dir(root) do
    bundles =
      case File.ls(root) do
        {:ok, entries} ->
          entries
          |> Enum.sort()
          |> Enum.map(fn entry -> Path.join(root, entry) end)
          |> Enum.filter(&File.dir?/1)
          |> Enum.map(&parse_bundle/1)
          |> Enum.reject(&is_nil/1)

        {:error, _} ->
          []
      end

    intro = """
    # ESR Bundle / SessionTemplate Reference

    Generated from each bundle's `manifest.yaml` + `template.yaml`. The
    canonical source is `runtime/lib/esr/bundles/<name>/`; do not edit this
    file directly. Regenerate with `mix esr.gen_bundle_docs`.

    Each bundle bundles together one SessionTemplate + dependency declarations.
    See `docs/notes/concepts.md` rev-11 §七a for the Bundle / SessionTemplate /
    Channel concept layering.

    """

    body =
      case bundles do
        [] ->
          "_No bundles registered — `runtime/lib/esr/bundles/` is empty._\n"

        list ->
          Enum.map_join(list, "\n", &render_bundle/1)
      end

    @banner <> "\n" <> intro <> body
  end

  # ------------------------------------------------------------------
  # Internals
  # ------------------------------------------------------------------

  # Parse one bundle dir. Returns `nil` on parse failure (with a Mix log
  # line so the operator sees what was skipped — but we don't fail the
  # whole task for one bad bundle; the CI gate `mix esr.check_bundles`
  # is the strict sibling).
  defp parse_bundle(dir) do
    manifest_path = Path.join(dir, "manifest.yaml")
    template_path = Path.join(dir, "template.yaml")

    cond do
      not File.regular?(manifest_path) ->
        Mix.shell().error("gen_bundle_docs: missing manifest.yaml at #{dir}; skipping")
        nil

      not File.regular?(template_path) ->
        Mix.shell().error("gen_bundle_docs: missing template.yaml at #{dir}; skipping")
        nil

      true ->
        with {:ok, manifest} <- Esr.Bundle.Manifest.parse(manifest_path),
             {:ok, template_content} <- File.read(template_path),
             {:ok, template} <-
               Esr.SessionTemplate.Parser.parse(template_content,
                 dependencies: manifest.dependencies,
                 verify_channels: false,
                 verify_flow_nodes: false
               ) do
          %{
            dir: dir,
            manifest: manifest,
            template: template,
            # In-tree bundles always have :bundle source; operator
            # ad-hoc templates aren't surfaced by this task (see moduledoc).
            source: {:bundle, manifest.name}
          }
        else
          {:error, reason} ->
            Mix.shell().error(
              "gen_bundle_docs: parse failed for #{dir}: #{inspect(reason)}; skipping"
            )

            nil
        end
    end
  end

  defp render_bundle(%{manifest: m, template: t, source: source}) do
    """
    ## `#{m.name}`

    **version:** `#{m.version}`

    **description:** #{m.description}

    **source:** `#{render_source(source)}`

    **dependencies:**
    #{render_dependencies(m.dependencies)}

    **channels:**
    #{render_channels(t.channels)}

    **agents:**
    #{render_agents(t.agents)}

    **flow:**
    #{render_flow(t.flow)}
    """
  end

  defp render_source({:bundle, name}), do: "bundle (#{name})"
  defp render_source(:operator), do: "operator"

  defp render_dependencies(%{plugins: plugins, bundles: bundles}) do
    plugin_str =
      case plugins do
        [] -> "_(none)_"
        list -> Enum.map_join(list, ", ", &"`#{&1}`")
      end

    bundle_str =
      case bundles do
        [] -> "_(none)_"
        list -> Enum.map_join(list, ", ", &"`#{&1}`")
      end

    "  - plugins: #{plugin_str}\n  - bundles: #{bundle_str}"
  end

  defp render_channels([]), do: "  _(none declared)_"

  defp render_channels(list) do
    Enum.map_join(list, "\n", fn ch ->
      config_str = render_config(ch.config)
      "  - alias `#{ch.alias}` → kind `#{ch.kind}`#{config_str}"
    end)
  end

  defp render_config(config) when map_size(config) == 0, do: ""

  defp render_config(config) do
    pairs =
      config
      |> Enum.sort_by(fn {k, _v} -> to_string(k) end)
      |> Enum.map_join(", ", fn {k, v} -> "#{k}=`#{format_value(v)}`" end)

    " (config: #{pairs})"
  end

  defp format_value(v) when is_binary(v), do: v
  defp format_value(v), do: inspect(v)

  defp render_agents([]), do: "  _(none declared)_"

  defp render_agents(list) do
    Enum.map_join(list, "\n", fn a ->
      consumes_str =
        case a.consumes do
          [] -> "_(consumes nothing)_"
          c -> Enum.map_join(c, ", ", &"`#{&1}`")
        end

      "  - kind `#{a.kind}` name `#{a.name}` consumes #{consumes_str}"
    end)
  end

  defp render_flow(%{inbound: inbound, outbound: outbound}) do
    inbound_section =
      case inbound do
        [] -> "  - inbound: _(none)_"
        _ -> "  - inbound:\n" <> Enum.map_join(inbound, "\n", &render_inbound_entry/1)
      end

    outbound_section =
      case outbound do
        [] -> "  - outbound: _(none)_"
        _ -> "  - outbound:\n" <> Enum.map_join(outbound, "\n", &render_outbound_entry/1)
      end

    inbound_section <> "\n" <> outbound_section
  end

  defp render_inbound_entry(%{source: source, pipeline: pipeline}) do
    pipeline_str =
      pipeline
      |> Enum.map(&format_pipeline_entry/1)
      |> Enum.join(" → ")

    "    - `#{source}` → #{pipeline_str}"
  end

  defp render_outbound_entry(%{source: source, sink: sink}) do
    "    - `#{source}` → sink `#{sink}`"
  end

  defp format_pipeline_entry({:builtin, name}), do: "`#{name}`"
  defp format_pipeline_entry({:module, mod}) when is_atom(mod), do: "`#{inspect(mod)}`"
  defp format_pipeline_entry({:unresolved, name}), do: "`#{name}`"
  defp format_pipeline_entry(name) when is_binary(name), do: "`#{name}`"
  defp format_pipeline_entry(other), do: "`#{inspect(other)}`"
end
