defmodule Mix.Tasks.Esr.CheckCommandDocs do
  @moduledoc """
  CI gate (Phase 4/6 of unified-command-grammar). Verifies every
  generated artifact under `runtime/priv/slash-routes.default.yaml` and
  `docs/grammar/{commands,errors}.md` matches the in-memory output of
  its emitter.

  ## Usage

      mix esr.check_command_docs

  Exits 0 (`✅ … in sync …`) when every artifact matches its emitter;
  exits 1 with a regenerate hint on first mismatch.

  ## Banner handling

  Each artifact has an AUTOGENERATED banner that is part of the file
  but excluded from the content-diff (so trivial banner edits — e.g. a
  copyright year — don't masquerade as drift). The banner itself MUST
  be present, however; a missing banner means someone hand-edited the
  file and stripped the marker, which is structural drift.

  Phase 5 wires this task into `.github/workflows/ci.yml`.
  """

  use Mix.Task

  @shortdoc "Verify slash-routes.yaml + docs/grammar/* are in sync with command_meta/0"

  @impl Mix.Task
  def run(_args) do
    Mix.Task.run("compile")
    {:ok, _} = Application.ensure_all_started(:esr)

    case check() do
      :ok ->
        Mix.shell().info("✅ slash-routes.yaml + docs/grammar/* in sync with command_meta/0")
        :ok

      {:error, file, reason} ->
        Mix.shell().error("❌ drift detected in #{file}: #{reason}")
        Mix.shell().error("regenerate with: mix esr.gen_slash_routes && mix esr.gen_command_docs")
        # Use exit/1 so test isolation can trap, mix run can fail.
        System.halt(1)
    end
  end

  @doc """
  Pure check — returns `:ok` or `{:error, file, reason}`. Used by
  `run/1` and by tests so the failure path is asserted without
  invoking `System.halt/1`.
  """
  @spec check() :: :ok | {:error, String.t(), String.t()}
  def check do
    repo_root = Path.expand("..", File.cwd!())

    artifacts = [
      {Path.join(File.cwd!(), "priv/slash-routes.default.yaml"),
       fn -> Mix.Tasks.Esr.GenSlashRoutes.emit() end},
      {Path.join(repo_root, "docs/grammar/commands.md"),
       fn -> Mix.Tasks.Esr.GenCommandDocs.emit_commands_md() end},
      {Path.join(repo_root, "docs/grammar/errors.md"),
       fn -> Mix.Tasks.Esr.GenCommandDocs.emit_errors_md() end}
    ]

    Enum.reduce_while(artifacts, :ok, fn {path, emitter}, _ ->
      case verify_one(path, emitter) do
        :ok -> {:cont, :ok}
        {:error, reason} -> {:halt, {:error, path, reason}}
      end
    end)
  end

  defp verify_one(path, emitter) do
    if File.exists?(path) do
      on_disk = File.read!(path)

      try do
        verify_banner!(on_disk, path)
        generated = emitter.()

        if strip_banner(on_disk) == strip_banner(generated) do
          :ok
        else
          {:error, "content differs from emitter output"}
        end
      rescue
        e -> {:error, Exception.message(e)}
      end
    else
      {:error, "file missing"}
    end
  end

  @doc """
  Strip every leading banner block from `content`. Two banner forms are
  recognised:

    * `# ...` line-comment block at top of file (yaml)
    * `<!-- ... -->` HTML-comment block at top of file (markdown)

  Trailing whitespace after the banner is also dropped so banners with
  surrounding blank lines round-trip.

  Public for testing — both `verify_banner!/2` and the diff path call it.
  """
  @spec strip_banner(String.t()) :: String.t()
  def strip_banner(content) when is_binary(content) do
    content
    |> strip_yaml_banner()
    |> strip_html_banner()
    |> String.trim_leading()
  end

  defp strip_yaml_banner(content) do
    # Strip a contiguous `# ...` block at the top (each line starts with `#`),
    # plus blank lines that follow.
    lines = String.split(content, "\n")

    {banner_lines, rest_lines} =
      Enum.split_while(lines, fn line ->
        String.starts_with?(line, "#") or line == ""
      end)

    if Enum.any?(banner_lines, &String.starts_with?(&1, "#")) do
      Enum.join(rest_lines, "\n")
    else
      content
    end
  end

  defp strip_html_banner(content) do
    case Regex.run(~r/\A<!--.*?-->\s*/s, content, return: :index) do
      [{0, len}] -> binary_part(content, len, byte_size(content) - len)
      nil -> content
    end
  end

  @doc """
  Raise if `content` does not start with the AUTOGENERATED banner
  marker. Path is included in the message for triage.
  """
  @spec verify_banner!(String.t(), String.t()) :: :ok | no_return()
  def verify_banner!(content, path) when is_binary(content) and is_binary(path) do
    if String.contains?(content, "AUTOGENERATED — DO NOT EDIT BY HAND") do
      :ok
    else
      raise "missing AUTOGENERATED banner in #{path} — file was hand-edited or banner was stripped"
    end
  end
end
